endpoints:
  - name: "Plex Media Server"
    group: external
    url: "https://plex.${PUBLIC_DOMAIN}:32400/identity"
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
      - "[BODY].MediaContainer.claimed == 1"
    alerts:
      - type: pushover
    headers:
      Accept: "application/json"
