endpoints:
  - name: "Plex Media Server"
    group: external
    url: "https://plex.${PUBLIC_DOMAIN}/web"
    interval: 5m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
