apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-snapshot-cronjob
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
     template:
        spec:
          serviceAccountName: vault-snapshotter
          volumes:
            - name: share
              emptyDir: {}
          containers:
          - name: backup
            image: hashicorp/vault:1.18.2@sha256:2090eb7ac7a4bdef802f685698bd4dc0740de683affe8ff7df55f4fc77077ba7
            imagePullPolicy: IfNotPresent
            env:
            - name: VAULT_ADDR
              value: https://vault.${PUBLIC_DOMAIN}:8200
            command: ["/bin/sh", "-c"]
            args:
              - >
                SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
                export VAULT_TOKEN=$(vault write -field=token auth/kubernetes/login jwt=$SA_TOKEN role=vault-snapshotter);
                vault operator raft snapshot save /share/vault-raft.snap;
            volumeMounts:
              - name: share
                mountPath: "/share"
          - name: snapshotupload
            image: amazon/aws-cli:2.22.10@sha256:98ef6a2bc9496032dbca3c6d723c41af82161f3ba5d883def9df9d04ff8bc93c
            imagePullPolicy: IfNotPresent
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-credentials-secret
                    key: access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-credentials-secret
                    key: secret-access-key
            command:
            - /bin/sh
            args:
            - -ec
            - |
                until [ -f /share/vault-raft.snap ]; do sleep 5; done;
                aws --endpoint-url=${S3URL} s3 cp /share/vault-raft.snap s3://backups/vault/vault_raft_$(date +"%Y%m%d_%H%M%S").snap;
            volumeMounts:
            - mountPath: /share
              name: share
          restartPolicy: OnFailure
