---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret radarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: "{{ .RADARR_API_KEY }}"
        RADARR__POSTGRES__HOST: &dbHost postgres17-rw.database.svc.cluster.local
        RADARR__POSTGRES__PORT: "5432"
        RADARR__POSTGRES__USER: &dbUser "{{ .RADARR_POSTGRES_USER }}"
        RADARR__POSTGRES__PASSWORD: &dbPass "{{ .RADARR_POSTGRES_PASSWORD }}"
        RADARR__POSTGRES__MAINDB: &dbName radarr
        PUSHOVER_TOKEN: "{{ .RADARR_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: secrets/cloudnative-pg
    - extract:
        key: secrets/pushover
    - extract:
        key: secrets/api-keys
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret radarr-oauth2-proxy-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.cfg: |
          code-challenge-method = "S256"
          http_address = "0.0.0.0:4180"
          provider = "oidc"
          redirect_url = "https://radarr.${PUBLIC_DOMAIN}/oauth2/callback"
          oidc_issuer_url = "https://auth.${PUBLIC_DOMAIN}/application/o/415f53bd-96e7-4ca0-972b-29036d2dabc6/"
          upstreams = [
              "http://127.0.0.1:80"
          ]
          email_domains = [
              "*"
          ]
          client_id = "{{ .RADARR_OIDC_CLIENT_ID }}"
          client_secret = "{{ .RADARR_OIDC_CLIENT_SECRET }}"
          pass_access_token = true
          cookie_secret = "{{ .RADARR_COOKIE_SECRET_KEY }}"
          skip_provider_button = true
  dataFrom:
    - extract:
        key: secrets/authentik
