---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret radarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: "{{ .RADARR_API_KEY }}"
        RADARR__POSTGRES__HOST: &dbHost postgres17-rw.database.svc.cluster.local
        RADARR__POSTGRES__PORT: "5432"
        RADARR__POSTGRES__USER: &dbUser "{{ .RADARR_POSTGRES_USER }}"
        RADARR__POSTGRES__PASSWORD: &dbPass "{{ .RADARR_POSTGRES_PASSWORD }}"
        RADARR__POSTGRES__MAINDB: &dbName radarr
        PUSHOVER_TOKEN: "{{ .RADARR_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
        CLIENT_SECRET: "{{ .CLIENT_SECRET}}"
        CLIENT_ID: "{{ .CLIENT_ID }}"
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: secrets/cloudnative-pg
    - extract:
        key: secrets/pushover
    - extract:
        key: secrets/api-keys
    - extract:
        key: secrets/oauth2/radarr
    - extract:
        key: secrets/redis
