---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: openebs-zfs-1m
spec:
  cloneStrategy: snapshot
  claimPropertySets:
    - accessModes:
      - ReadWriteOnce
      volumeMode: Filesystem
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: openebs-zfs-128k
spec:
  cloneStrategy: snapshot
  claimPropertySets:
    - accessModes:
      - ReadWriteOnce
      volumeMode: Filesystem
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: openebs-zfs-32k
spec:
  cloneStrategy: snapshot
  claimPropertySets:
    - accessModes:
      - ReadWriteOnce
      volumeMode: Filesystem
