---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: darkfellanet
spec:
  secretName: darkfellanet-tls
  issuerRef:
    name: zerossl-prod
    kind: ClusterIssuer
  commonName: ${PUBLIC_DOMAIN}
  dnsNames:
    - ${PUBLIC_DOMAIN}
    - "external.${PUBLIC_DOMAIN}"
    - "flux-webhook.${PUBLIC_DOMAIN}"
    - "status.${PUBLIC_DOMAIN}"
