---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: darkfellanet-tls
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: darkfellanet-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: certificates/darkfellanet
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: certificates/darkfellanet
          property: *key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-server-tls
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik-server-tls
  template:
    engineVersion: v2
    data:
      ca.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: certificates/authentik
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: certificates/authentik
          property: *key
    - match:
        secretKey: &key ca.crt
        remoteRef:
          remoteKey: certificates/authentik
          property: *key
