---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  CLUSTER: '{{.CLUSTER | default "main"}}'
  CLUSTER_DIR: '{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}'

env:
  KUBECONFIG: '{{.CLUSTER_DIR}}/kubeconfig'
  TALOSCONFIG: '{{.CLUSTER_DIR}}/talosconfig'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'

includes:
  bootstrap: .taskfiles/bootstrap

tasks:

  default: task --list
