---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      volumes:
        - name: host-run-netns
          hostPath:
            path: /var/run/netns/
      initContainers:
        - name: install-multus-binary
          image: ghcr.io/buroa/multus-cni:dev@sha256:873788c07144c6339fde6b734b67208f425a533607a7d915291f0f46bad92084
        - name: install-cni
          image: ghcr.io/siderolabs/install-cni:v1.9.0
          command:
            - /install-cni.sh
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              mountPropagation: Bidirectional
              name: cnibin
      containers:
        - name: kube-multus
          image: ghcr.io/buroa/multus-cni:dev@sha256:873788c07144c6339fde6b734b67208f425a533607a7d915291f0f46bad92084
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 50Mi
