apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: krb5.conf
data:
  krb5.conf: |
    [logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log

    [libdefaults]
    dns_lookup_realm = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    pkinit_anchors = /etc/pki/tls/certs/ca-bundle.crt
    default_ccache_name = KEYRING:persistent:%{uid}

    default_realm = ${AD_REALM}

    [realms]
    YOUR-REALM.COM = {
      kdc = dc01.${PUBLIC_DOMAIN}
      admin_server = dc01.${PUBLIC_DOMAIN}
    }

    [domain_realm]
    ${PUBLIC_DOMAIN} = ${AD_REALM}
    .${PUBLIC_DOMAIN} = ${AD_REALM}
