---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  image: ghcr.io/darkfella91/keycloak:latest@sha256:fe3ff754ac29c7004b8ce55fe67658a1f775a50607ae2a224b89e4a5bca1c8e2
  startOptimized: true
  imagePullSecrets:
    - name: github-credentials
  hostname:
    hostname: https://auth.darkfellanetwork.com
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: external.darkfellanetwork.com
    className: external
  additionalOptions:
    - name: KC_BOOTSTRAP_ADMIN_USERNAME
      value: admin
    - name: KC_BOOTSTRAP_ADMIN_PASSWORD
      secret:
        name: admin-credentials
        key: password
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: init-db
            image: "ghcr.io/onedr0p/postgres-init:16.4@sha256:e41c745b54485341e00efbd27556f0717623a119f0d5107e5ff831aa1322c76f"
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: keycloak-initdb-secret
