---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  image: ghcr.io/darkfella91/keycloak:latest@sha256:f48529f651cfb51d96554b9a3a81a732b22f096e2ab9b1dd2d9b6d278cc75a33
  startOptimized: true
  imagePullSecrets:
    - name: github-credentials
  hostname:
    hostname: https://auth.${PUBLIC_DOMAIN}
  http:
    httpEnabled: false
    httpsPort: 443
    tlsSecret: keycloak-tls
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: internal.${PUBLIC_DOMAIN}
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    className: internal
  additionalOptions:
    - name: proxy
      value: passthrough
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: init-db
            image: "ghcr.io/onedr0p/postgres-init:16.4@sha256:e41c745b54485341e00efbd27556f0717623a119f0d5107e5ff831aa1322c76f"
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: keycloak-initdb-secret
