---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  image: ghcr.io/darkfella91/keycloak:latest@sha256:435132674c7b91dd91e865e299275a8aba9217fafe1551c3fea21262000a92d9
  startOptimized: true
  imagePullSecrets:
    - name: github-credentials
  hostname:
    hostname: https://auth.${PUBLIC_DOMAIN}
    admin: https://auth-admin.${PUBLIC_DOMAIN}
  http:
    tlsSecret: keycloak-tls
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
      nginx.ingress.kubernetes.io/modsecurity-snippet: |
            SecAction "id:900200, phase:1, pass, t:none, nolog, setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE PATCH"
    className: external
  unsupported:
    podTemplate:
      spec:
        containers:
          - volumeMounts:
              - name: cert
                mountPath: /etc/ssl/custom
        volumes:
          - name: cert
            secret:
              secretName: keycloak-tls
        initContainers:
          - name: init-db
            image: "ghcr.io/onedr0p/postgres-init:16.4@sha256:e41c745b54485341e00efbd27556f0717623a119f0d5107e5ff831aa1322c76f"
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: keycloak-initdb-secret
