---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  image: ghcr.io/darkfella91/keycloak:latest@sha256:bd9d01bf6343e6d4ac2bbcb39a00247ff7ffdd8e603bf082aadae907f20c8864
  startOptimized: true
  imagePullSecrets:
    - name: github-credentials
  hostname:
    hostname: https://auth.${PUBLIC_DOMAIN}
  http:
    tlsSecret: keycloak-tls
    httpEnabled: false
    strict: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    className: external
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: init-db
            image: "ghcr.io/onedr0p/postgres-init:16.4@sha256:e41c745b54485341e00efbd27556f0717623a119f0d5107e5ff831aa1322c76f"
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: keycloak-initdb-secret
