---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: idp
  annotations:
    external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: zerossl-prod
    cert-manager.io/private-key-rotation-policy: always
    cert-manager.io/private-key-algorithm: Ed25519
spec:
  ingressClassName: external
  tls:
    - hosts:
        - &host accounts.${PUBLIC_DOMAIN}
      secretName: keycloak-tls
  rules:
    - host: *host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 443
