---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: crowdsec-cnpg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
    resizeInUseVolumes: true
  walStorage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
    resizeInUseVolumes: true
  superuserSecret:
    name: &secret cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 400Mi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      dataChecksums: true
      database: crowdsec
      owner: crowdsec
