---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: crowdsec-cnpg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-19
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: topolvm-provisioner-thin
  superuserSecret:
    name: &secret cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: true
