---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: secrets/cloudnative-pg
        property: super_user
    - secretKey: password
      remoteRef:
        key: secrets/cloudnative-pg
        property: super_user_pass
    - secretKey: accessKeyId
      remoteRef:
        key: secrets/cloudflare
        property: accessKeyId
    - secretKey: secretAccessKey
      remoteRef:
        key: secrets/cloudflare
        property: secretAccessKey
