---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gatus-cnpg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
    resizeInUseVolumes: true
  walStorage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
    resizeInUseVolumes: true
  superuserSecret:
    name: &secret cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    limits:
      cpu: '4'
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 400Mi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: gzip
        encryption: AES256
      wal:
        compression: gzip
        encryption: AES256
        maxParallel: 8
      destinationPath: s3://gatus/cnpg
      endpointURL: ${S3URL}
      # Note: serverName version needs to be inclemented
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster v1
      s3Credentials:
        accessKeyId:
          name: *secret
          key: CF_ACCESS_KEY_ID
        secretAccessKey:
          name: *secret
          key: CF_SECRET_ACCESS_KEY
  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  #externalClusters:
    #- name: *previousCluster
      #barmanObjectStore:
        #<<: *barmanObjectStore
        #serverName: *previousCluster
