---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-cnpg
spec:
  superuserSecret:
    name: &secret cloudnative-pg-secret
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: gzip
        encryption: AES256
        jobs: 2
      destinationPath: s3://backups/vaultwarden/cnpg
      endpointURL: ${S3URL}
      s3Credentials:
        accessKeyId:
          key: CF_ACCESS_KEY_ID
          name: *secret
        secretAccessKey:
          key: CF_SECRET_ACCESS_KEY
          name: *secret
      serverName: &currentCluster v1
      wal:
        compression: gzip
        encryption: AES256
        maxParallel: 8
  bootstrap:
    recovery:
      source: &previousCluster vaultwarden-cnpg-main-1
  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster
  enablePDB: true
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  instances: 2
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 400Mi
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    resizeInUseVolumes: true
  walStorage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
    resizeInUseVolumes: true
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
