---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: flaresolverr
spec:
  interval: 30m
  chart:
    spec:
      chart: flaresolverr
      version: 15.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
