---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: darkfellanet-tls
spec:
  externalSecretName: darkfellanet-tls
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - authentik
          - network
          - vault
  refreshTime: 5m
  externalSecretSpec:
    refreshInterval: 5m
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      name: darkfellanet-tls
      creationPolicy: Orphan
      template:
        engineVersion: v2
        type: kubernetes.io/tls
        metadata:
          annotations:
            cert-manager.io/alt-names: '*.${PUBLIC_DOMAIN},${PUBLIC_DOMAIN}'
            cert-manager.io/certificate-name: darkfellanet
            cert-manager.io/common-name: ${PUBLIC_DOMAIN}
            cert-manager.io/ip-sans: ""
            cert-manager.io/issuer-group: ""
            cert-manager.io/issuer-kind: ClusterIssuer
            cert-manager.io/issuer-name: zerossl-prod
            cert-manager.io/uri-sans: ""
          labels:
            controller.cert-manager.io/fao: "true"
    dataFrom:
      - extract:
          key: secrets/certificates/darkfellanet
          decodingStrategy: Auto
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: authentik-server-tls
spec:
  externalSecretName: authentik-server-tls
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - authentik
  refreshTime: 5m
  externalSecretSpec:
    refreshInterval: 5m
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      name: authentik-server-tls
      creationPolicy: Orphan
      template:
        engineVersion: v2
        type: kubernetes.io/tls
        metadata:
          annotations:
            cert-manager.io/alt-names: 'authentik.authentik.svc.cluster.local'
            cert-manager.io/certificate-name: authentik
            cert-manager.io/common-name: authentik.authentik.svc.cluster.local
            cert-manager.io/ip-sans: ""
            cert-manager.io/issuer-group: ""
            cert-manager.io/issuer-kind: ClusterIssuer
            cert-manager.io/issuer-name: zerossl-prod
            cert-manager.io/uri-sans: ""
          labels:
            controller.cert-manager.io/fao: "true"
    dataFrom:
      - extract:
          key: secrets/certificates/authentik
          decodingStrategy: Auto
