---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret autobrr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"
        AUTOBRR_POSTGRESS_ENCODED_PASS: "{{ .AUTOBRR_POSTGRESS_ENCODED_PASS }}"
        INIT_POSTGRES_USER: "{{ .AUTOBRR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTOBRR_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
        CLIENT_SECRET: "{{ .CLIENT_SECRET}}"
        CLIENT_ID: "{{ .CLIENT_ID }}"
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: secrets/autobrr
    - extract:
        key: secrets/cloudnative-pg
    - extract:
        key: secrets/oauth2/autobrr
    - extract:
        key: secrets/redis
