---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret autobrr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: &dbName autobrr
        AUTOBRR__POSTGRES_HOST: &dbHost postgres17-rw.database.svc.cluster.local
        AUTOBRR__POSTGRES_USER: &dbUser "{{ .AUTOBRR_POSTGRES_USER }}"
        AUTOBRR__POSTGRES_PASS: "{{ .AUTOBRR_POSTGRESS_PASS }}"
        AUTOBRR__POSTGRES_PORT: "5432"
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: "{{ .AUTHENTIK_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: secrets/autobrr
    - extract:
        key: secrets/cloudnative-pg
