---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autobrr
spec:
  interval: 30m
  chart:
    spec:
      verify:
        provider: cosign
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      autobrr:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.6@sha256:c1d3a845d47fe1aeebd110fefb5f43f54c4735aec1d2b0c01de8d4d5e8cdd6a4
            env:
              INIT_POSTGRES_DBNAME: &dbName autobrr
              INIT_POSTGRES_HOST: &dbHost postgres17-rw.database.svc.cluster.local
              INIT_POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: &secret autobrr-secret
                    key: INIT_POSTGRES_USER
              INIT_POSTGRES_PASS:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: INIT_POSTGRES_PASS
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: INIT_POSTGRES_SUPER_PASS

        containers:
          app:
            image:
              repository: ghcr.io/autobrr/autobrr
              tag: v1.55.0@sha256:227b0592cb91809edf000f67ea12192a74d83213c8c8ed3c6ece9cac7b59e821
            env:
              AUTOBRR__CHECK_FOR_UPDATES: "false"
              AUTOBRR__HOST: 0.0.0.0
              AUTOBRR__PORT: &port 80
              AUTOBRR__LOG_LEVEL: INFO
              AUTOBRR__DATABASE_TYPE: postgres
              AUTOBRR__POSTGRES_DATABASE: *dbName
              AUTOBRR__POSTGRES_HOST: *dbHost
              AUTOBRR__POSTGRES_PORT: 5432
              AUTOBRR__SESSION_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: AUTOBRR__SESSION_SECRET
              AUTOBRR__POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: INIT_POSTGRES_USER
              AUTOBRR__POSTGRES_PASS:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: AUTOBRR_POSTGRESS_ENCODED_PASS
              AUTOBRR__OIDC_ENABLED: "true"
              AUTOBRR__OIDC_ISSUER: https://accounts.darkfellanetwork.com/realms/DarkfellaNET
              AUTOBRR__OIDC_CLIENT_ID: f710a9b4-4404-46a3-8831-5377aab29185
              AUTOBRR__OIDC_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: AUTOBRR__OIDC_CLIENT_SECRET
              AUTOBRR__OIDC_REDIRECT_URL: https://autobrr.darkfellanetwork.com/api/auth/oidc/callback
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["/bin/sh", "-c", "curl -s http://localhost/api/healthz/liveness | grep 'OK' > /dev/null"]
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["/bin/sh", "-c", "curl -s http://localhost/api/healthz/readiness | grep 'OK' > /dev/null"]
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: autobrr
        ports:
          http:
            port: *port

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${PUBLIC_DOMAIN}
          cert-manager.io/cluster-issuer: zerossl-prod
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
        className: internal
        tls:
          - hosts:
              - &host "{{ .Release.Name }}.${PUBLIC_DOMAIN}"
            secretName: autobrr-tls
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      tmp:
        type: emptyDir
