---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: autobrr-loki-rules
    files:
      - autobrr.yaml=./resources/lokirule.yaml
    options:
      labels:
        loki_rule: "true"
  - name: autobrr-gatus-ep
    options:
      labels:
        gatus.io/enabled: "true"
    files:
      - config.yaml=./resources/gatus-ep.yaml
  - name: autobrr-oauth2-proxy-config
    files:
      - oauth2-proxy.cfg=./resources/oauth2-proxy.cfg
generatorOptions:
  disableNameSuffixHash: true
