---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
spec:
  interval: 30m
  chart:
    spec:
      chart: descheduler
      version: 0.31.0
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    replicas: 1
    kind: Deployment
    deschedulerPolicyAPIVersion: descheduler/v1alpha1  # Use the correct API version
    deschedulerPolicy:
      profiles:
        - name: SingleNodePolicy
          plugins:
            deschedule:
              enabled:
                - RemoveFailedPods
          pluginConfig:
            - name: RemoveFailedPods
              args:
                failedPods:
                  excludeOwnerKinds: []  # Include all types of failed pods
                  reasons:
                    - Evicted
                    - NodeAffinity
                    - NodeLost
                    - FailedScheduling
                  minPodLifetimeSeconds: 60
                  includingInitContainers: true
    evictLocalStoragePods: true  # Enable eviction in single-node clusters
    tolerateUnreadyNodes: true   # Tolerate unready nodes to allow single-node operation
    service:
      enabled: true
    serviceMonitor:
      enabled: true
    leaderElection:
      enabled: false
