---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-truenas-1
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-truenas-1",
      "type": "bridge",
      "bridge": "br0",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.91.39/24",
            "gateway": "192.168.91.1"
          }
        ],
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "192.168.91.1" }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-truenas-2
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-truenas-2",
      "type": "bridge",
      "bridge": "br0",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.91.40/24",
            "gateway": "192.168.91.1"
          }
        ],
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "192.168.91.1" }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-windows-server
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-windows-server",
      "type": "bridge",
      "bridge": "br0",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.91.41/24",
            "gateway": "192.168.91.1"
          }
        ],
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "192.168.91.1" }
        ]
      }
    }'
