apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: client-intents-for-nginx-external-controller
  namespace: network
spec:
  service:
    name: nginx-external-controller
  calls:
    - name: "notification-controller.flux-system"
    - name: "keycloak.idp"
    - name: "jellyseerr.media"
    - name: "plex.media"
    - name: "nginx-external-defaultbackend"
    - name: "nginx-internal-controller"
    - name: "oauth2-proxy.oauth2-proxy"
    - name: "gatus.observability"
    - name: "vaultwarden.vaultwarden"
    - type: internet
      internet:
        domains:
          - crowdsec-api.darkfellanetwork.com
          - crowdsec-appsec.darkfellanetwork.com
