---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret nginx-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        BOUNCER_API_KEY: "{{ .BOUNCER_API_KEY }}"
  dataFrom:
    - extract:
        key: secrets/maxmind
    - extract:
        key: secrets/api-keys
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret crowdsec-bouncer-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        crowdsec-bouncer.conf: |
          ENABLED=true
          API_URL=http://crowdsec-service.network.svc.cluster.local:8080
          API_KEY={{ .BOUNCER_API_KEY }}
          CACHE_EXPIRATION=1
          BOUNCING_ON_TYPE=all
          FALLBACK_REMEDIATION=ban
          REQUEST_TIMEOUT=3000
          UPDATE_FREQUENCY=10
          ENABLE_INTERNAL=false
          MODE=live
          EXCLUDE_LOCATION=
          BAN_TEMPLATE_PATH=/etc/nginx/lua/plugins/crowdsec/templates/ban.html
          RET_CODE=403
          SSL_VERIFY=true
  dataFrom:
    - extract:
        key: secrets/crowdsec
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret nginx-external-dhparam
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        dhparam.pem: "{{ .dhparam.pem }}"
  dataFrom:
    - extract:
        key: secrets/nginx-external
