---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./config
configMapGenerator:
  - name: nginx-error-pages
    files:
      - 504.html=./error-pages/504.html.yaml
      - 504.json=./error-pages/504.json.yaml
      - 503.html=./error-pages/503.html.yaml
      - 503.json=./error-pages/503.json.yaml
      - 502.html=./error-pages/502.html.yaml
      - 502.json=./error-pages/502.json.yaml
      - 501.html=./error-pages/501.html.yaml
      - 501.json=./error-pages/501.json.yaml
      - 500.html=./error-pages/500.html.yaml
      - 500.json=./error-pages/500.json.yaml
      - 429.html=./error-pages/429.html.yaml
      - 410.html=./error-pages/410.html.yaml
      - 404.html=./error-pages/404.html.yaml
      - 404.json=./error-pages/404.json.yaml
      - 403.html=./error-pages/403.html.yaml
      - 403.json=./error-pages/403.json.yaml
      - 400.html=./error-pages/400.html.yaml
generatorOptions:
  disableNameSuffixHash: true
