apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: limit
spec:
  buffering:
    maxRequestBodyBytes: 1000000000
    memRequestBodyBytes: 100000000
    memResponseBodyBytes: 0
    maxResponseBodyBytes: 0
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-ratelimit
spec:
  rateLimit:
    average: 100
    burst: 50
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-secure-headers
spec:
  headers:
    frameDeny: true
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - HEAD
      - PUT
    accessControlMaxAge: 100
    browserXssFilter: true
    contentTypeNosniff: true
    customRequestHeaders:
      X-Forwarded-Proto: https
    customResponseHeaders:
      server: ''
      x-powered-by: ''
    stsIncludeSubdomains: true
    forceSTSHeader: true
    referrerPolicy: same-origin
    stsSeconds: 63072000
    stsPreload: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
spec:
  compress:
    excludedContentTypes:
      - image/*
      - audio/*
      - video/*
      - application/octet-stream
      - application/pdf
      - application/zip
      - application/font-*
      - application/vnd.ms-fontobject
      - application/x-font-ttf
      - application/gzip
      - application/zip
      - application/x-tar
      - application/x-7z-compressed
    minResponseBodyBytes: 512
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-basic
spec:
  chain:
    middlewares:
      - name: basic-ratelimit
      - name: basic-secure-headers
      - name: compress
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: realip
spec:
  plugin:
    traefik-real-ip:
      excludednets:
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: local
spec:
  ipAllowList:
    sourceRange:
      - 192.168.91.0/24
      - 172.16.0.0/16
      - 172.17.0.0/16
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bazarr
spec:
  plugin:
    traefik-themepark:
      app: bazarr
      baseUrl: https://theme-park.${PUBLIC_DOMAIN}
      theme: mind
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: radarr
spec:
  plugin:
    traefik-themepark:
      app: radarr
      baseUrl: https://theme-park.${PUBLIC_DOMAIN}
      theme: mind
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sonarr
spec:
  plugin:
    traefik-themepark:
      app: sonarr
      baseUrl: https://theme-park.${PUBLIC_DOMAIN}
      theme: mind
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prowlarr
spec:
  plugin:
    traefik-themepark:
      app: prowlarr
      baseUrl: https://theme-park.${PUBLIC_DOMAIN}
      theme: mind
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: vuetorrent
spec:
  plugin:
    traefik-themepark:
      app: vuetorrent
      baseUrl: https://theme-park.${PUBLIC_DOMAIN}
      theme: mind
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sabnzbd
spec:
  plugin:
    traefik-themepark:
      app: sabnzbd
      baseUrl: https://theme-park.${PUBLIC_DOMAIN}
      theme: mind
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: overseerr
spec:
  plugin:
    traefik-themepark:
      app: overseerr
      baseUrl: https://theme-park.${PUBLIC_DOMAIN}
      theme: mind
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bouncer
spec:
  plugin:
    crowdsec-bouncer-traefik-plugin:
      clientTrustedIPs:
        - 172.16.0.0/16
        - 172.17.0.0/16
        - 192.168.91.0/24
      crowdsecAppsecEnabled: false
      crowdsecLapiHost: crowdsec-service.network.svc.cluster.local:8080
      crowdsecLapiScheme: https
      crowdsecLapiTLSCertificateAuthorityFile: /etc/traefik/crowdsec-certs/ca.crt
      crowdsecLapiTLSCertificateBouncerFile: /etc/traefik/crowdsec-certs/tls.crt
      crowdsecLapiTLSCertificateBouncerKeyFile: /etc/traefik/crowdsec-certs/tls.key
      crowdsecMode: stream
      enabled: true
      forwardedHeadersCustomName: CF-Connecting-IP
      forwardedHeadersTrustedIPs:
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
      logLevel: INFO
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik
spec:
  forwardAuth:
    address: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-authentik-username
      - X-authentik-groups
      - X-authentik-email
      - X-authentik-name
      - X-authentik-uid
      - X-authentik-jwt
      - X-authentik-meta-jwks
      - X-authentik-meta-outpost
      - X-authentik-meta-provider
      - X-authentik-meta-app
      - X-authentik-meta-version
      - authorization
