---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret qbitmanage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
  dataFrom:
    - extract:
        key: secrets/qbittorrent
