---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbitmanage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: media
  values:
    controllers:
      qbitmanage:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          copy-secret:
            image:
              repository: busybox
              tag: 1.37.0@sha256:768e5c6f5cb6db0794eec98dc7a967f40631746c32232b78a3105fb946f3ab83
            command: ['sh', '-c', 'cp /secrets/config.yml /config/config.yml']
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        containers:
          app:
            image:
              repository: ghcr.io/stuffanthings/qbit_manage
              tag: v4.1.11@sha256:ad120c350a3781a19f165178f70582d2260a67f9e40795f29b54edf3ba8861b2
            env:
              TZ: Europe/Sofia
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1024Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    persistence:
      config:
        type: emptyDir
      secret-file:
        type: secret
        name: qbitmanage-secret
        advancedMounts:
          qbitmanage:
            copy-secret:
              - path: /secrets/config.yml
                subPath: config.yml
                readOnly: true
      qbittorrent-config:
        existingClaim: qbittorrent-config
        advancedMounts:
          qbitmanage:
            app:
              - path: /qBittorrent/BT_backup
                subPath: qBittorrent/BT_backup
                readOnly: true
      torrents:
        type: nfs
        server: nas.${PUBLIC_DOMAIN}
        path: /mnt/exos20/data
        advancedMounts:
          qbitmanage:
            app:
              - path: /data/downloads/torrents
                subPath: downloads/torrents
