---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: topolvm
      namespace: kube-system

  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.41.1.9057-af5eaea7a@sha256:5926b77196bb7c9f75b52f431d0483abea0fef1f576b7201592b385449201456
            env:
              TZ: Europe/Sofia
              PLEX_ADVERTISE_URL: https://plex.${PUBLIC_DOMAIN}:443,http://192.168.91.98:32400
              PLEX_UID: 568
              PLEX_GID: 568
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 3Gi
                nvidia.com/gpu: 1

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: plex
        type: LoadBalancer
        allocateLoadBalancerNodePorts: false
        annotations:
          lbipam.cilium.io/ips: 192.168.91.98
        ports:
          http:
            port: 32400

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/enable-modsecurity: "true"
          nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
          nginx.ingress.kubernetes.io/modsecurity-snippet: |
            Include /etc/nginx/modsecurity/modsecurity.conf
            Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header referrer-policy "same-origin" always;
            add_header x-frame-options sameorigin;
            add_header x-content-type-options "nosniff" always;
            more_set_headers "access-control-allow-origin https://plex.${PUBLIC_DOMAIN}";
            more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'unsafe-eval' 'sha256-n58YmpdcR3n0/CPQrOOiI18yviz0Fjcq4nLR+NZP2LU=' 'sha256-pKO/nNgeauDINvYfxdygP3mGssdVQRpRNxaF7uPRoGM=' 'sha256-GcwLRDW7XyLvQjVnUDDeLp/npZkD9vkKUHdIa+PCuPM=' 'sha256-LoTcf31kQmt04dfWTgmy5714ZqP/EaxcLHv0fpAFYns=' 'sha384-/5F7awMQXrAyZU+oaIp5envqh0ZPaZeuvsk7ZcpXM5rVBbOToK5SocqjzScbHgi1' 'sha384-GnXe70SAt+PPEoi15r3SnJTgy0aRQ1zu6oEXQ4lSuNMrhtSwn2v8NvdaaYcTPFPA' 'report-sample' https://www.gstatic.com 'self' https://plex.${PUBLIC_DOMAIN} https://*.plex.tv 'strict-dynamic'; style-src 'sha256-ZdHxw9eWtnxUb3mk6tBS+gIiVUPE3pGM470keHPDFlE=' 'report-sample' 'self' 'unsafe-hashes' https://fonts.googleapis.com; style-src-attr 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; connect-src 'self' https://plex.${PUBLIC_DOMAIN} wss://plex.${PUBLIC_DOMAIN} https://*.ingest.sentry.io https://plex.tv https://*.plex.tv https://*.plex.direct https://*.plex.direct:32400 wss://*.plex.direct wss://*.plex.direct:32400 https://*.plex.services wss://pubsub.plex.tv wss://plex.tv wss://*.syncplay.plex.services:7777 wss://*.syncplay.plex.services:7776; font-src 'self' https://fonts.gstatic.com; frame-src 'self' https://*.plex.direct:*; frame-ancestors 'none'; img-src 'self' https://plex.${PUBLIC_DOMAIN} https://*.plex.tv https://plex.tv blob: data: https://*.plex.direct:*; manifest-src 'self'; media-src 'self' https://plex.${PUBLIC_DOMAIN} https://video.internetvideoarchive.net data: blob: https://*.plex.direct:*; worker-src 'none'; form-action 'self'; upgrade-insecure-requests";
        className: external
        hosts:
          - host: "{{ .Release.Name }}.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: ImplementationSpecific
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: persistentVolumeClaim
        size: 100Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server

      logs:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Logs

      tmp:
        type: emptyDir
        medium: Memory

      transcode:
        type: persistentVolumeClaim
        size: 200Gi
        accessMode: ReadWriteOnce

      media:
        type: nfs
        server: nas.${PUBLIC_DOMAIN}
        path: /mnt/exos20/data
        globalMounts:
          - path: /data/media
            readOnly: true
            subPath: media
