---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: crowdsec-external-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: crowdsec
        INIT_POSTGRES_HOST: crowdsec-cnpg-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .CROWDSEC_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .CROWDSEC_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        ENROLL_KEY: "{{ .ENROLL_KEY }}"
  dataFrom:
    - extract:
        key: secrets/cloudnative-pg
    - extract:
        key: secrets/crowdsec
