---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret crowdsec-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: crowdsec
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .CROWDSEC_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .CROWDSEC_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        ENROLL_KEY: "{{ .ENROLL_KEY }}"
  dataFrom:
    - extract:
        key: secrets/cloudnative-pg
    - extract:
        key: secrets/crowdsec
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret crowdsec-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        http.yaml: |
          #########################################################################
          # Title:            CrowdSec : Pushover Notification (API)              #
          # Author(s):        JigSawFr                                            #
          # URL:              https://github.com/crowdsecurity/crowdsec           #
          #########################################################################
          #                             MIT License                               #
          #########################################################################

          type: http
          name: pushover

          # One of "trace", "debug", "info", "warn", "error", "off"
          log_level: info

          # group_wait: "30s"        # Time to wait collecting alerts before relaying a message to this plugin, eg "30s"
          # group_threshold: 10   # Amount of alerts that triggers a message before <group_wait> has expired, eg "10"
          # max_retry: 5         # Number of attempts to relay messages to plugins in case of error
          # timeout: "10s"           # Time to wait for response from the plugin before considering the attempt a failure, eg "10s"

          #-------------------------
          # plugin-specific options

          # The following template receives a list of models.Alert objects
          # The output goes in the http request body
          format: |
            {
            "token": "{{ .CROWDSEC_PUSHOVER_TOKEN }}",
            "user": "{{ .PUSHOVER_USER_KEY }}",
            "message": "{{`{{range . -}}{{$alert := . -}}{{range .Decisions -}}<b>{{.Value}}</b> will get <b>{{.Type}}</b> for the next <b>{{.Duration}}</b> for triggering <b>{{.Scenario}}</b>.\r\n https://www.shodan.io/host/{{.Value}}{{end -}}{{end -}}`}}",
            "html": "1",
            "title": "Scenario triggered on IDS/IPS !"
            }
          url: https://api.pushover.net/1/messages.json
          method: POST
          headers:
            Content-Type: "application/json"
        profiles.yaml: |
          name: default_ip_remediation
          #debug: true
          filters:
          - Alert.Remediation == true && Alert.GetScope() == "Ip"
          decisions:
          - type: ban
            duration: 4h
          duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 4)
          notifications:
            - pushover
          on_success: break
          ---
          name: default_range_remediation
          #debug: true
          filters:
          - Alert.Remediation == true && Alert.GetScope() == "Range"
          decisions:
          - type: ban
            duration: 4h
          duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 4)
          notifications:
            - pushover
          on_success: break
  dataFrom:
    - extract:
        key: secrets/pushover
