---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: crowdsec-external-secret
    template:
      engineVersion: v2
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secrets/cloudnative-pg
        property: CROWDSEC_PASSWORD
    - secretKey: ENROLL_KEY
      remoteRef:
        key: secrets/crowdsec
        property: ENROLL_KEY
