---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 30m
  chart:
    spec:
      chart: sonarr
      version: 23.1.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    securityContext:
      container:
        readOnlyRootFilesystem: true
    credentials:
      s3:
        type: s3
        bucket: backups
    persistence:
      config:
        size: 5Gi
        volsync:
          - name: config
            type: restic
            credentials: s3
            src:
              enabled: true
              cacheCapacity: 5Gi
            dest:
              cacheCapacity: 5Gi
              enabled: true
      media:
        enabled: true
        type: nfs
        path: &nfs_path /mnt/exos20/data
        server: &nfs_host nas.${PUBLIC_DOMAIN}
        mountPath: /data/media
        subPath: media
      backup:
        enabled: true
        type: nfs
        path: *nfs_path
        server: *nfs_host
        mountPath: /config/backup
        subPath: backups/radarr
