---
# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/heads/master/traefik/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 32.1.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
  values:
    tlsStore:
        default:
          certificates:
            - secretName: darkfellanet-tls
          defaultCertificate:
            secretName: darkfellanet-tls
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    deployment:
      annotations:
        reloader.stakater.com/auto: "true"
      ingressClass:
        enabled: true
        isDefaultClass: true
        name: internal
      enabled: true
      kind: Deployment
      replicas: 2
      revisionHistoryLimit: 5
      terminationGracePeriodSeconds: 60
      minReadySeconds: 0
      healthchecksPort: 9000
      healthchecksScheme: HTTP
      additionalVolumes:
        - name: plugins
      shareProcessNamespace: false
      dnsPolicy: ""
      dnsConfig: {}
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: false
        allowEmptyServices: true
        ingressClass: internal
        namespaces: []
        nativeLBByDefault: false
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: false
        allowEmptyServices: true
        ingressClass: internal
        namespaces: []
        publishedService:
          enabled: false
        nativeLBByDefault: false
    additionalVolumeMounts:
      - name: plugins
        mountPath: /plugins-storage
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    metrics:
      addInternals: false
      prometheus:
        entryPoint: metrics
        addEntryPointsLabels: null
        addRoutersLabels: null
        addServicesLabels: null
        buckets: ""
        manualRouting: false
        service:
          enabled: true
          labels: {}
          annotations: {}
        disableAPICheck: false
    globalArguments:
      - --global.checknewversion
    additionalArguments:
      - --experimental.plugins.traefik-themepark.modulename=github.com/packruler/traefik-themepark
      - --experimental.plugins.traefik-themepark.version=v1.4.1
    ports:
      web:
        expose:
          default: false
      websecure:
        asDefault: true
        port: 443
        targetPort: 443
        protocol: TCP
        transport:
          respondingTimeouts:
            readTimeout: null
            writeTimeout: null
            idleTimeout: null
          lifeCycle:
            requestAcceptGraceTimeout: null
            graceTimeOut: null
          keepAliveMaxRequests: null
          keepAliveMaxTime: null
        tls:
          enabled: true
        middlewares:
          - network-chain-internal@kubernetescrd
      metrics:
        port: 9100
        expose:
          default: false
        exposedPort: 9100
        protocol: TCP
    tlsOptions:
      default:
        sniStrict: true
        minVersion: VersionTLS13
        curvePreferences:
          - CurveP521
          - CurveP384
          - X25519
    service:
      enabled: true
      single: true
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/ips: 192.168.91.97
        external-dns.alpha.kubernetes.io/hostname: internal.${PUBLIC_DOMAIN}
      spec:
        allocateLoadBalancerNodePorts: false
    autoscaling:
      enabled: false
    hostNetwork: false
    rbac:
      enabled: true
      namespaced: false
