---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret authentik-global-vars-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_EMAIL__FROM: "{{ .AUTHENTIK_EMAIL__FROM }}"
        AUTHENTIK_EMAIL__HOST: "{{ .AUTHENTIK_EMAIL__HOST }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .SMTP_AUTHENTIK_PASS }}"
        AUTHENTIK_EMAIL__PORT: "587"
        AUTHENTIK_EMAIL__USERNAME: "{{ .SMTP_USERNAME }}"
        AUTHENTIK_EMAIL__USE_TLS: "true"
        AUTHENTIK_POSTGRESQL__HOST: "postgres17-rw.database.svc.cluster.local"
        AUTHENTIK_POSTGRESQL__NAME: "authentik"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_POSTGRES_PASS }}"
        AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_POSTGRES_USER }}"
        AUTHENTIK_REDIS__HOST: "redis-master.database.svc.cluster.local"
        AUTHENTIK_REDIS__PASSWORD: "{{ .AUTHENTIK_REDIS__PASSWORD }}"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_STORAGE__MEDIA__BACKEND: "s3"
        AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: "{{ .CF_ACCESS_KEY_ID__AUTHENTIK}}"
        AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: "{{ .CF_SECRET_ACCESS_KEY__AUTHENTIK}}"
        AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: "authentik-media"
        AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: "{{ .CF_S3_ENDPOINT__AUTHENTIK}}"
        AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: "s3.provider/authentik-media"
  dataFrom:
    - extract:
        key: secrets/authentik
    - extract:
        key: secrets/redis
    - extract:
        key: secrets/cloudflare
    - extract:
        key: secrets/cloudnative-pg
    - extract:
        key: secrets/Brevo
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret authentik-initdb-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: authentik
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .AUTHENTIK_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTHENTIK_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: secrets/cloudnative-pg
