---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.8.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      deploymentAnnotations:
        reloader.stakater.com/auto: "true"
      envFrom:
        - secretRef:
            name: authentik-global-vars-secret
      volumes:
        - name: cert
          secret:
            secretName: darkfellanet-tls
            optional: false
      volumeMounts:
        - name: cert
          mountPath: /certs
          readOnly: true
    server:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
          nginx.ingress.kubernetes.io/modsecurity-snippet: |
            Include /etc/nginx/owasp-modsecurity-crs/authentik-crs-setup.conf;
        ingressClassName: external
        hosts:
          - authentik.${PUBLIC_DOMAIN}
        paths:
          - /
        pathType: Prefix
      initContainers:
        - name: init-db
          image: "ghcr.io/onedr0p/postgres-init:16.3@sha256:9c136223fb4e05b0ca24e2350c2dc45843110d0e1d09615c52c9a037628c09fa"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: authentik-initdb-secret
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
      volumeMounts:
        - name: media
          mountPath: /media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
