---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.10.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      deploymentAnnotations:
        reloader.stakater.com/auto: "true"
      envFrom:
        - secretRef:
            name: authentik-global-vars-secret
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    server:
      containerSecurityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccomProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "access-control-allow-origin https://authentik.${PUBLIC_DOMAIN}";
          nginx.ingress.kubernetes.io/modsecurity-snippet: |
            SecAction "id:900200, phase:1, pass, t:none, nolog, setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE PATCH"
        ingressClassName: external
        hosts:
          - authentik.${PUBLIC_DOMAIN}
        paths:
          - /
        pathType: Prefix
      initContainers:
        - name: init-db
          image: "ghcr.io/onedr0p/postgres-init:16.4@sha256:e41c745b54485341e00efbd27556f0717623a119f0d5107e5ff831aa1322c76f"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: authentik-initdb-secret
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
      volumeMounts:
        - name: media
          mountPath: /media
          readOnly: true
    worker:
      containerSecurityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccomProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      volumes:
        #- name: default
          #emptyDir: {}
        - name: certs
          projected:
            sources:
            - secret:
                name: darkfellanet-tls
        #- name: blueprints
          #configMap:
            #name: blueprints
      volumeMounts:
        #- name: blueprints
          #mountPath: /blueprints/custom
          #readOnly: false
        - name: certs
          mountPath: /certs
          readOnly: true
        #- name: default
          #mountPath: /blueprints/default
