---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./blueprints
  - ./externalsecret.yaml
  - ./helm-release.yaml
  - ../../../../templates/gatus/external
configMapGenerator:
  - name: blueprints
    files:
      - brand.yaml=./blueprints/brand.yaml
      - authentication-flow.yaml=./blueprints/authentication-flow.yaml
      - totp-authenticator-flow.yaml=./blueprints/totp-authenticator-flow.yaml
      - authenticator-validation-stage.yaml=./blueprints/authenticator-validation-stage.yaml
      - password-stage.yaml=./blueprints/password-stage.yaml
      - identification-stage.yaml=./blueprints/identification-stage.yaml
      - identification-stage-recovery.yaml=./blueprints/identification-stage-recovery.yaml
      - email-confirmation-stage.yaml=./blueprints/email-confirmation-stage.yaml
      - email-confirmation-stage-with-user-activation.yaml=./blueprints/email-confirmation-stage-with-user-activation.yaml
      - email-confirmation-stage-recovery.yaml=./blueprints/email-confirmation-stage-recovery.yaml
generatorOptions:
  disableNameSuffixHash: true
