apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win-2k25
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: win-2k25
    spec:
      networks:
       - name: default
         pod: {}
      domain:
        clock:
          timezone: Europe/Sofia
          timer: {}
        cpu:
          cores: 2
          model: host-passthrough
        features:
          acpi: {}
          apic: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
          uuid: c9db879b-5e87-455e-bb16-4ed27d77e522
        devices:
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          tpm: {}
          disks:
            - disk:
                bus: virtio
              name: root-disk
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
      volumes:
      - dataVolume:
          name: win-2k25-1
        name: root-disk
  dataVolumeTemplates:
  - metadata:
      name: win-2k25-1
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 64Gi
      source:
        pvc:
          namespace: virtualization
          name: win2k25
