---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret oauth2-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        redis-password: "{{ .REDIS_PASSWORD }}"
        cookie-secret: "{{ .OAUTH2_COOKIE_SECRET }}"
        client-secret: "{{ .OAUTH2_CLIENT_SECRET }}"
        client-id: "{{ .OAUTH2_CLIENT_ID }}"
  dataFrom:
    - extract:
        key: secrets/redis
    - extract:
        key: secrets/oauth2
