---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret notifiarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        DN_API_KEY: "{{ .DN_API_KEY }}"
        DN_UI_PASSWORD: "{{ .DN_UI_PASSWORD }}"
        DN_UPSTREAMS_0: "{{ .DN_UPSTREAMS_0 }}"
        TMPDIR: "{{ .TMPDIR }}"
        DN_BIND_ADDR: "{{ .DN_BIND_ADDR }}"
        DN_MODE: "{{ .DN_MODE }}"
        DN_PLEX_TOKEN: "{{ .DN_PLEX_TOKEN }}"
        DN_PLEX_URL: "{{ .DN_PLEX_URL }}"
        DN_PROWLARR_0_API_KEY: "{{ .DN_PROWLARR_0_API_KEY }}"
        DN_PROWLARR_0_NAME: "{{ .DN_PROWLARR_0_NAME }}"
        DN_PROWLARR_0_URL: "{{ .DN_PROWLARR_0_URL }}"
        DN_QBIT_0_NAME: "{{ .DN_QBIT_0_NAME }}"
        DN_QBIT_0_URL: "{{ .DN_QBIT_0_URL }}"
        DN_QBIT_0_USER: "{{ .DN_QBIT_0_USER }}"
        DN_QBIT_0_PASS: "{{ .DN_QBIT_0_PASS }}"
        DN_RADARR_0_API_KEY: "{{ .DN_RADARR_0_API_KEY }}"
        DN_RADARR_0_NAME: "{{ .DN_RADARR_0_NAME }}"
        DN_RADARR_0_URL: "{{ .DN_RADARR_0_URL }}"
        DN_SABNZBD_0_API_KEY: "{{ .DN_SABNZBD_0_API_KEY }}"
        DN_SABNZBD_0_NAME: "{{ .DN_SABNZBD_0_NAME }}"
        DN_SABNZBD_0_URL: "{{ .DN_SABNZBD_0_URL }}"
        DN_SONARR_0_API_KEY: "{{ .DN_SONARR_0_API_KEY }}"
        DN_SONARR_0_NAME: "{{ .DN_SONARR_0_NAME }}"
        DN_SONARR_0_URL: "{{ .DN_SONARR_0_URL }}"

  dataFrom:
    - extract:
        key: secrets/notifiarr
