---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vaultwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: vaultwarden
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      registry: docker.io
      repository: vaultwarden/server
      tag: 1.32.2-alpine
      pullPolicy: IfNotPresent
    commonAnnotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      - name: init-db
        image: ghcr.io/onedr0p/postgres-init:16
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: vaultwarden-initdb-secret
    podSecurityContext:
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsGroup: 1001
      runAsUser: 1001
      capabilities:
        drop:
          - ALL
    data:
      name: vaultwarden-data
      size: 15Gi
      path: /data
      keepPvc: false
      accessMode: ReadWriteOnce
    attachments:
      name: vaultwarden-files
      size: 100Gi
      path: /files
      keepPvc: false
      accessMode: ReadWriteOnce
    webVaultEnabled: true
    database:
      type: postgresql
      existingSecret: &secret vaultwarden-secret
      existingSecretKey: VAULTWARDEN_DATABASE_URI
    eventsDayRetain: 14
    domain: https://vaultwarden.${PUBLIC_DOMAIN}
    sendsAllowed: true
    trashAutoDeleteDays: 14
    signupsAllowed: true
    signupsVerify: true
    signupDomains: ${PUBLIC_DOMAIN}
    invitationsAllowed: true
    invitationOrgName: Vaultwarden
    ipHeader: X-Real-IP
    iconBlacklistNonGlobalIps: true
    requireDeviceEmail: true
    adminToken:
      existingSecret: *secret
      existingSecretKey: VAULTWARDEN_ADMIN_TOKEN
    timeZone: Europe/Sofia
    smtp:
      existingSecret: *secret
      host: smtp-relay.brevo.com
      security: starttls
      port: 587
      from: noreply@${BASE_DOMAIN}
      fromName: DarkfellaNET
      username:
        existingSecretKey: SMTP_USERNAME
      password:
        existingSecretKey: SMTP_VAULTWARDEN_PASS
      authMechanism: Login
    ingress:
      enabled: true
      additionalAnnotations:
        external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
        kubernetes.io/ingress.class: external
      hostname: vaultwarden.${PUBLIC_DOMAIN}
      path: /
      pathType: Prefix
