---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: vaultwarden-gatus-ep
    files:
      - config.yaml=./resources/gatus-ep.yaml
generatorOptions:
  disableNameSuffixHash: true
