---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: guarded
        url: "https://${GATUS_SUBDOMAIN:-${APP}}.${PUBLIC_DOMAIN}${GATUS_PATH:-/}"
        interval: 10m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://172.17.0.10:53
        conditions:
          - [STATUS] == 200
          - [BODY].status == OK
        alerts:
          - type: pushover
