---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret bazarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        BAZARR__AUTH__APIKEY: "{{ .BAZARR_API_KEY }}"
        BAZARR__POSTGRES__HOST: &dbHost postgres17-rw.database.svc.cluster.local
        BAZARR__POSTGRES__PORT: "5432"
        BAZARR__POSTGRES__USER: &dbUser "{{ .BAZARR_POSTGRES_USER }}"
        BAZARR__POSTGRES__PASSWORD: &dbPass "{{ .BAZARR_POSTGRES_PASS }}"
        BAZARR__POSTGRES__MAINDB: &dbName bazarr
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: secrets/plex
    - extract:
        key: secrets/api-keys
    - extract:
        key: secrets/cloudnative-pg
