---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret bazarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        POSTGRES_ENABLED: "true"
        POSTGRES_HOST: &dbHost postgres17-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USERNAME: &dbUser "{{ .BAZARR_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .BAZARR_POSTGRES_PASS }}"
        POSTGRES_DATABASE: &dbName bazarr
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: secrets/plex
    - extract:
        key: secrets/api-keys
    - extract:
        key: secrets/cloudnative-pg
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret bazarr-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          addic7ed:
            cookies: ''
            password: ''
            user_agent: ''
            username: ''
            vip: false
          analytics:
            enabled: false
          anidb:
            api_client: ''
            api_client_ver: 1
          animetosho:
            anidb_api_client: ''
            anidb_api_client_ver: 1
            search_threshold: 6
          anticaptcha:
            anti_captcha_key: ''
          assrt:
            token: ''
          auth:
            apikey: "{{ .BAZARR_API_KEY}}"
            password: ''
            type: null
            username: ''
          avistaz:
            cookies: ''
            user_agent: ''
          backup:
            day: 6
            folder: /config/backup
            frequency: Weekly
            hour: 3
            retention: 31
          betaseries:
            token: ''
          cinemaz:
            cookies: ''
            user_agent: ''
          cors:
            enabled: false
          deathbycaptcha:
            password: ''
            username: ''
          embeddedsubtitles:
            fallback_lang: en
            hi_fallback: true
            included_codecs: []
            timeout: 600
            unknown_as_fallback: false
          general:
            adaptive_searching: true
            adaptive_searching_delay: 3w
            adaptive_searching_delta: 1w
            anti_captcha_provider: null
            auto_update: false
            base_url: ''
            branch: master
            chmod: '0640'
            chmod_enabled: false
            days_to_upgrade_subs: 7
            debug: false
            default_und_audio_lang: ''
            default_und_embedded_subtitles_lang: ''
            dont_notify_manual_actions: false
            embedded_subs_show_desired: true
            embedded_subtitles_parser: ffprobe
            enabled_integrations: []
            enabled_providers:
            - subssabbz
            - subsunacs
            - yavkanet
            - embeddedsubtitles
            - opensubtitlescom
            flask_secret_key: "{{ .FLASK_SECRET_KEY }}"
            hi_extension: hi
            ignore_ass_subs: false
            ignore_pgs_subs: false
            ignore_vobsub_subs: false
            ip: '*'
            language_equals: []
            minimum_score: 90
            minimum_score_movie: 70
            movie_default_enabled: true
            movie_default_profile: 1
            movie_tag_enabled: false
            multithreading: true
            page_size: 25
            parse_embedded_audio_track: false
            path_mappings: []
            path_mappings_movie: []
            port: 6767
            postprocessing_cmd: /scripts/subcleaner.sh {{"{{"}}subtitles{{"}}"}}
            postprocessing_threshold: 90
            postprocessing_threshold_movie: 70
            remove_profile_tags: []
            serie_default_enabled: true
            serie_default_profile: 1
            serie_tag_enabled: false
            single_language: false
            skip_hashing: false
            subfolder: current
            subfolder_custom: ''
            subzero_mods: remove_HI
            theme: auto
            upgrade_frequency: 12
            upgrade_manual: true
            upgrade_subs: true
            use_embedded_subs: false
            use_postprocessing: true
            use_postprocessing_threshold: false
            use_postprocessing_threshold_movie: false
            use_radarr: true
            use_scenename: true
            use_sonarr: true
            utf8_encode: true
            wanted_search_frequency: 6
            wanted_search_frequency_movie: 6
          hdbits:
            passkey: ''
            username: ''
          jimaku:
            api_key: ''
            enable_ai_subs: false
            enable_archives_download: false
            enable_name_search_fallback: true
          karagarga:
            f_password: ''
            f_username: ''
            password: ''
            username: ''
          ktuvit:
            email: ''
            hashed_password: ''
          legendasdivx:
            password: ''
            skip_wrong_fps: false
            username: ''
          legendasnet:
            password: ''
            username: ''
          log:
            exclude_filter: ''
            ignore_case: false
            include_filter: ''
            use_regex: false
          movie_scores:
            audio_codec: 3
            edition: 1
            hash: 119
            hearing_impaired: 1
            release_group: 13
            resolution: 2
            source: 7
            streaming_service: 1
            title: 60
            video_codec: 2
            year: 30
          napisy24:
            password: ''
            username: ''
          opensubtitles:
            password: ''
            skip_wrong_fps: false
            ssl: false
            timeout: 15
            use_tag_search: false
            username: ''
            vip: false
          opensubtitlescom:
            include_ai_translated: false
            password: "{{ .OPENSUBTITLES_PASS }}"
            use_hash: true
            username: "{{ .OPENSUBTITLES_USER }}"
          podnapisi:
            verify_ssl: true
          postgresql:
            database: ''
            enabled: false
            host: localhost
            password: ''
            port: 5432
            username: ''
          proxy:
            exclude:
            - localhost
            - 127.0.0.1
            password: ''
            port: ''
            type: null
            url: ''
            username: ''
          radarr:
            apikey: "{{ .RADARR_API_KEY }}"
            base_url: ''
            defer_search_signalr: false
            excluded_tags: []
            full_update: Daily
            full_update_day: 6
            full_update_hour: 4
            http_timeout: 60
            ip: radarr.${PUBLIC_DOMAIN}
            movies_sync: 60
            only_monitored: false
            port: 443
            ssl: true
            sync_only_monitored_movies: false
            use_ffprobe_cache: true
          series_scores:
            audio_codec: 3
            episode: 30
            hash: 359
            hearing_impaired: 1
            release_group: 14
            resolution: 2
            season: 30
            series: 180
            source: 7
            streaming_service: 1
            video_codec: 2
            year: 90
          sonarr:
            apikey: "{{ .SONARR_API_KEY }}"
            base_url: ''
            defer_search_signalr: false
            exclude_season_zero: false
            excluded_series_types: []
            excluded_tags: []
            full_update: Daily
            full_update_day: 6
            full_update_hour: 4
            http_timeout: 60
            ip: sonarr.${PUBLIC_DOMAIN}
            only_monitored: false
            port: 443
            series_sync: 60
            ssl: true
            sync_only_monitored_episodes: false
            sync_only_monitored_series: false
            use_ffprobe_cache: true
          subdl:
            api_key: ''
          subf2m:
            user_agent: ''
            verify_ssl: true
          subsync:
            checker:
              blacklisted_languages: []
              blacklisted_providers: []
            debug: false
            force_audio: false
            gss: true
            max_offset_seconds: 60
            no_fix_framerate: false
            subsync_movie_threshold: 99
            subsync_threshold: 99
            use_subsync: true
            use_subsync_movie_threshold: true
            use_subsync_threshold: true
          titlovi:
            password: ''
            username: ''
          titulky:
            approved_only: false
            password: ''
            username: ''
          whisperai:
            endpoint: http://127.0.0.1:9000
            loglevel: INFO
            response: 5
            timeout: 3600
          xsubs:
            password: ''
            username: ''
  dataFrom:
    - extract:
        key: secrets/opensubtitles
    - extract:
        key: secrets/api-keys
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret bazarr-gatus-ep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      metadata:
        labels:
          gatus.io/enabled: "true"
      engineVersion: v2
      data:
        config.yaml: |
          endpoints:
            - name: "bazarr"
              group: guarded
              url: "https://bazarr.${PUBLIC_DOMAIN}/api/system/status"
              interval: 5m
              ui:
                hide-hostname: true
                hide-url: true
              client:
                dns-resolver: tcp://172.17.0.10:53
              conditions:
                - "[STATUS] == 200"
                - "has([BODY].data.bazarr_version) == true"
              alerts:
                - type: pushover
              headers:
                Accept: application/json
                X-API-KEY: {{ .BAZARR_API_KEY }}
  dataFrom:
    - extract:
        key: secrets/api-keys
