---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bazarr
spec:
  interval: 30m
  chart:
    spec:
      chart: bazarr
      version: 21.1.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - targetPath: credentials.s3.url
      kind: Secret
      name: &secret backup-credentials
      valuesKey: CF_S3_ENDPOINT
    - targetPath: credentials.s3.accessKey
      kind: Secret
      name: *secret
      valuesKey: CF_ACCESS_KEY_ID
    - targetPath: credentials.s3.secretKey
      kind: Secret
      name: *secret
      valuesKey: CF_SECRET_ACCESS_KEY
    - targetPath: credentials.s3.encrKey
      kind: Secret
      name: *secret
      valuesKey: CF_SECRET_ACCESS_KEY
  values:
    credentials:
      s3:
        type: s3
        bucket: cluster-6740-bazarr
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 5Gi
              enabled: true
              storageClassName: &storage topolvm-provisioner-thin
              volumeSnapshotClassName: *storage
            src:
              enabled: true
              cacheCapacity: 5Gi
              storageClassName: *storage
              volumeSnapshotClassName: *storage
      data:
        enabled: true
        type: nfs
        path: /mnt/exos20/data
        subPath: media
        mountPath: /data/media
        server: nas.{PUBLIC_DOMAIN}
      backup:
        enabled: true
        type: nfs
        path: /mnt/exos20/data
        subPath: backups
        mountPath: /config/backup
        server: nas.{PUBLIC_DOMAIN}
    securityContext:
      container:
        readOnlyRootFilesystem: true
    metrics:
      main:
        enabled: true
