---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
spec:
  interval: 30m
  chart:
    spec:
      chart: bazarr
      version: 21.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - targetPath: credentials.s3.url
      kind: Secret
      name: &secret volsync-backup-credentials
      valuesKey: CF_S3_ENDPOINT
    - targetPath: credentials.s3.encrKey
      kind: Secret
      name: *secret
      valuesKey: ENCRYPTION_KEY
    - targetPath: credentials.s3.accessKey
      kind: Secret
      name: *secret
      valuesKey: CF_ACCESS_KEY_ID
    - targetPath: credentials.s3.secretKey
      kind: Secret
      name: *secret
      valuesKey: CF_SECRET_ACCESS_KEY
  values:
    credentials:
      s3:
        type: s3
        bucket: backups
    persistence:
      config:
        size: 5Gi
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 5Gi
              enabled: false
            src:
              enabled: true
              cacheCapacity: 5Gi
      data:
        enabled: true
        type: nfs
        path: &nfs_path /mnt/exos20/data
        server: &nfs_host nas.${PUBLIC_DOMAIN}
        mountPath: /media
        subPath: media
      backup:
        enabled: true
        type: nfs
        path: *nfs_path
        server: *nfs_host
        mountPath: /config/backup
        subPath: backups/bazarr
    securityContext:
      container:
        readOnlyRootFilesystem: true
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${PUBLIC_DOMAIN}
          kubernetes.io/ingress.class: internal
        hosts:
          - host: bazarr.${PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix

