---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-prod
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    privateKeySecretRef:
      name: zerossl-prod
    externalAccountBinding:
      keyID: ${EAB_KEY_ID}
      keySecretRef:
        name: &secret zerossl-credentials
        key: EAB_HMAC_KEY
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: *secret
              key: CF_API_TOKEN
