---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret vaultwarden-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        admin-token: "{{ .VAULTWARDEN_ADMIN_TOKEN }}"
        VAULTWARDEN_DATABASE_URI: "{{ .VAULTWARDEN_DATABASE_URI }}"
        smtp-user: "{{ .SMTP_USERNAME }}"
        smtp-password: "{{ .SMTP_VAULTWARDEN_PASS }}"
        SMTP_SENDER: "{{ .SMTP_SENDER }}"
        INIT_POSTGRES_DBNAME: vaultwarden
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .VAULTWARDEN_POSTGRESS_USER }}"
        INIT_POSTGRES_PASS: "{{ .VAULTWARDEN_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: secrets/vaultwarden
    - extract:
        key: secrets/Brevo
    - extract:
        key: secrets/cloudnative-pg
