---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: vaultwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      vaultwarden:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.6@sha256:35353a77777ee8f634d0f3945f495b4a40065134b8619e0d18bd49b0ee9c855b
            env:
              INIT_POSTGRES_DBNAME: vaultwarden
              INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
              INIT_POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: &secret vaultwarden-secret
                    key: INIT_POSTGRES_USER
              INIT_POSTGRES_PASS:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: INIT_POSTGRES_PASS
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: INIT_POSTGRES_SUPER_PASS

        containers:
          oauth2-proxy:
            image:
              repository: quay.io/oauth2-proxy/oauth2-proxy
              tag: v7.7.1-amd64@sha256:95f2002754cb0f1c1553aed56f4d6564a5b860e01baccb4e1b8311ffa25c167c
            args:
              - --config=/etc/oauth2-proxy.cfg
            env:
              OAUTH2_PROXY_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: CLIENT_ID
              OAUTH2_PROXY_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: CLIENT_SECRET
              OAUTH2_PROXY_COOKIE_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: COOKIE_SECRET
              OAUTH2_PROXY_REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: REDIS_PASSWORD
              OAUTH2_PROXY_SESSION_STORE_TYPE: redis
              OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis-master.database.svc.cluster.local:6379/4
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              runAsUser: 2000
              runAsGroup: 2000

          app:
            image:
              repository: vaultwarden/server
              tag: 1.32.5@sha256:84015c9306cc58f4be8b09c1adc62cfc3b2648b1430e9c15901482f3d870bd14
            env:
              EMAIL_2FA_ENFORCE_ON_VERIFIED_INVITE: true
              EMAIL_2FA_AUTO_FALLBACK: true
              AUTHENTICATOR_DISABLE_TIME_DRIFT: true
              REQUIRE_DEVICE_EMAIL: true
              DISABLE_ADMIN_TOKEN: true
              DATA_FOLDER: data
              ICON_CACHE_FOLDER: data/icon_cache
              ATTACHMENTS_FOLDER: data/attachments
              DOMAIN: https://vaultwarden.${PUBLIC_DOMAIN}
              TZ: "Europe/Sofia"
              EMAIL_CHANGE_ALLOWED: false
              SIGNUPS_ALLOWED: false
              SIGNUPS_VERIFY: true
              SIGNUPS_DOMAINS_WHITELIST: ${PUBLIC_DOMAIN}
              ROCKET_ADDRESS: 127.0.0.1
              SMTP_AUTH_MECHANISM: Login
              SMTP_HOST: smtp-relay.brevo.com.
              SMTP_FROM: noreply@${PUBLIC_DOMAIN}
              SMTP_FROM_NAME: vaultwarden
              SMTP_PORT: 587
              SMTP_SECURITY: starttls
              SMTP_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: SMTP_USERNAME
              SMTP_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: SMTP_PASSWORD
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: DATABASE_URL
              PUSH_ENABLED: true
              PUSH_INSTALLATION_ID:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: PUSH_INSTALLATION_ID
              PUSH_INSTALLATION_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: PUSH_INSTALLATION_KEY
              PUSH_RELAY_URI: https://api.bitwarden.eu
              PUSH_IDENTITY_URI: https://identity.bitwarden.eu
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 4180

    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
          cert-manager.io/cluster-issuer: zerossl-prod
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
        hosts:
          - host: &host vaultwarden.${PUBLIC_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        size: 15Gi
        accessMode: ReadWriteOnce
        storageClass: openebs-zfs-128k
        globalMounts:
          - path: /data

      oauth2-proxy-config:
        type: configMap
        name: vaultwarden-oauth2-proxy-config
        advancedMounts:
          vaultwarden:
            oauth2-proxy:
              - path: /etc/oauth2-proxy.cfg
                subPath: oauth2-proxy.cfg
                readOnly: true
