apiVersion: v1
kind: ConfigMap
metadata:
  name: password
data:
  password-stage.yaml: |
    version: 1
    metadata:
      name: Password Stage
    context:
      backends:
      - authentik.core.auth.InbuiltBackend
      # - authentik.sources.ldap.auth.LDAPBackend
      # - authentik.core.auth.TokenBackend
      password_change_flow_slug: 6ef43887-af21-4247-8bbf-d69e79e27e3c
      password_change_flow_blueprint_name: Flow - Password Change
    entries:
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_blueprints.metaapplyblueprint
      conditions:
      - !Context password_change_flow_blueprint_name
      - !Context password_change_flow_slug
      attrs:
        identifiers:
          name: !Context password_change_flow_blueprint_name
        required: true
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_stages_password.passwordstage
      id: password-stage
      identifiers:
        name: password-stage
      attrs:
        backends: !Context backends
        configure_flow: !Find [authentik_flows.flow, [slug, !Context password_change_flow_slug]]
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
