---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: guarded
        url: "https://${APP}.${PUBLIC_DOMAIN}${GATUS_PATH:-/}"
        interval: 10m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://172.17.0.10:53
        conditions:
          - "[STATUS] == 200"
          - "[BODY].version EXISTS"
        alerts:
          - type: pushover
