apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:KeiBfsOYbAilanRFWTniJY8iApE=,iv:6sdpiOX7gZODMfv0vwO9HlROX7vILjbvNkYofNQKzjE=,tag:dCJkFwrof79py5fJ1yLSWg==,type:str]
    EAB_KEY_ID: ENC[AES256_GCM,data:ndLcmUj76gb/PQ65+szPJkLiZf8b2Q==,iv:E6vKcUoVZaCdBaajCmaEE0ez+4MKSfh6xe6W9Iy1rts=,tag:LNlGqNVeiDBqBUaGEOiAvg==,type:str]
    S3URL: ENC[AES256_GCM,data:4eXYOQuo2tDd+kAXZfg2XNUltBjM3OfEX7CUTwaz9mqr6UHSnVFFl2nxwXaE92Df6TVOe66w2780s0tcHmeVM81pBi0=,iv:fgwPt4wdCtL0NP8Xuz+pFRrlCEBzQ2uN0HNPx96dS5c=,tag:6ZQTrqsJ6Mm89uQfm8Y/VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frhtpr8u3u99pvcuq5mjevxdq9agjfpkd8fjtnpj9qymzh5v845q53f37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T0RNbStKa0ttS3RiUk03
            WStycVN4dmhvUDBUT1o2a1R6Qnd5dkVPVFQ0ClozTS82RmlCc2o4TEQ2UGRoOGp3
            TDIxeGZHNSt1VHpGVkMweXA0RW5nY2sKLS0tIFJMeGMvWVdyRkpaVlMwa3ZBQis4
            QW1lVW5BaVpDR1JReEI2L3k1WGxwRW8KcjNPmPf05RKize92JHHw3qcWT3j5H7gE
            089qhWDhyldAZJAjJVK+6MJvFQj3JeCHHyAgfFsnhSWYBBoSCU48IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T03:11:42Z"
    mac: ENC[AES256_GCM,data:3mMwyeVe6Pzq+FfT5kYsNDnMC4q/rNBVZ4j5+ttmzSLlyG9HUmnkQ6JeZhoUqUlRe/Fxz9N2a1CjjfwiJa3Ti06b7e0FyeitsS+2ywSWdUxkmF7ZmStv8FtvbV1FjNYlWbkuZV5tsoe/HW1FnmV6GqXknEdoiA6X2uAoCUmls10=,iv:D5ofoZ3RwCzNzTKZNsEb98Rw6sn4XYORBbEt+x0uvqc=,tag:zIlp97ehxZFx/LMO1E0zrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.1
