apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:PwtYbcCui5UsC+rimZC5QNgwwZ+LZDQHjV4o+ARrWe53WIZf,iv:GVqwLq/4SR3sFj/0qRZ5SYt31j8ezGaeJsj6u6kQQqk=,tag:oBreoO25bpcGWcrImuugAg==,type:str]
    KERBEROS_PASSWORD: ENC[AES256_GCM,data:lZZho8xEGfnVSag50A==,iv:JmrrZymVwUiPQueOG3n9cmd5smN4B2fsojOwIpxVY60=,tag:V7WAqaEZWCFdA8DNZB1c8Q==,type:str]
    AWS_ACCESS_KEY: ENC[AES256_GCM,data:mPJ9xbM54GP9BkhOz/O7qaPsFk0=,iv:7SQQ2S89d7c0lVoxQP0JvbmpxELA8DXSYfCxaLBDF4I=,tag:tLQ/IVx6Dxuuq+K+I1vKhw==,type:str]
    AWS_SECRET_KEY: ENC[AES256_GCM,data:+acohLCugLGUY6iMpS7dVjMbMag4teGImMfC35MlQIvvpmY1HdhUqw==,iv:JzSTxol9vwjDbnihICmD5pkDazoX3GGdnNnCJzvaMdo=,tag:vaZvofDsjoPGE/G+1XPZ7Q==,type:str]
    AWS_KEY_ID: ENC[AES256_GCM,data:hLSFvhsaOzZF/2kEMKwD7bsk5QZTy2VAdDZcgRGDHjGjkQJFdVjsAROCV8T9pZ6ZuraCOjsGrBfq2/ZQ3+vYDOlKrTWBZh5DtlI4,iv:eDBs/XH6km+nOLuQ5ct1CnBPyObzgG9AA7zhsjcrES4=,tag:cW+ANHpGEbObt5wiPzIwJw==,type:str]
    CF_ACCESS_KEY_ID: ENC[AES256_GCM,data:gSFGMt/b/wgz8u1CmXtYmEWNTLmhMCMw+eZJ1JM6+FA=,iv:x5FVvz5pJh4YDIiMxRc2lGO2F9fCuZLGy5FaJOUe8OE=,tag:TBR4Cbiwl7S8S1lwWNACIw==,type:str]
    CF_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+UuNk+G8bxLEp6aPf6LsSEGQVCJFXeJ9U5bHPJ4BKzevuD04YZFbcOKm+BRW0H291RzUAl2Tj9/Bvbf2CBbf/w==,iv:XT6o5g72wZNfEj5iCFn7ZEuIwgEV3UNfolrv6VbmNN0=,tag:GhpUm3O8EqEQwA3UTMtyDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frhtpr8u3u99pvcuq5mjevxdq9agjfpkd8fjtnpj9qymzh5v845q53f37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T0RNbStKa0ttS3RiUk03
            WStycVN4dmhvUDBUT1o2a1R6Qnd5dkVPVFQ0ClozTS82RmlCc2o4TEQ2UGRoOGp3
            TDIxeGZHNSt1VHpGVkMweXA0RW5nY2sKLS0tIFJMeGMvWVdyRkpaVlMwa3ZBQis4
            QW1lVW5BaVpDR1JReEI2L3k1WGxwRW8KcjNPmPf05RKize92JHHw3qcWT3j5H7gE
            089qhWDhyldAZJAjJVK+6MJvFQj3JeCHHyAgfFsnhSWYBBoSCU48IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T09:32:41Z"
    mac: ENC[AES256_GCM,data:F7rssFyYlRpkcd+2iYu/zLHObREa3AZhzJhW7pgwXScCvshPJq/GSTmm8KS1ltH7VMABazhTne/k5CzzrjiPdZ8lQV4ursn2PzprT7YwxvEMpbu7pHSS+3vgQbzapl2qNsmk1kWWBfFNUKiREvJCqwQEAqAaKi2K/HdV+vAYenA=,iv:BD2j1czIZSz+L2xlM6xQfwf6dab1qEpZQ5Z/K0/mC0Y=,tag:Qw+Y1IuuMIF2Q3/8axSt0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.2
