apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  PUBLIC_DOMAIN: ENC[AES256_GCM,data:KeiBfsOYbAilanRFWTniJY8iApE=,iv:6sdpiOX7gZODMfv0vwO9HlROX7vILjbvNkYofNQKzjE=,tag:dCJkFwrof79py5fJ1yLSWg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1frhtpr8u3u99pvcuq5mjevxdq9agjfpkd8fjtnpj9qymzh5v845q53f37d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T0RNbStKa0ttS3RiUk03
        WStycVN4dmhvUDBUT1o2a1R6Qnd5dkVPVFQ0ClozTS82RmlCc2o4TEQ2UGRoOGp3
        TDIxeGZHNSt1VHpGVkMweXA0RW5nY2sKLS0tIFJMeGMvWVdyRkpaVlMwa3ZBQis4
        QW1lVW5BaVpDR1JReEI2L3k1WGxwRW8KcjNPmPf05RKize92JHHw3qcWT3j5H7gE
        089qhWDhyldAZJAjJVK+6MJvFQj3JeCHHyAgfFsnhSWYBBoSCU48IQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-11T20:37:32Z"
  mac: ENC[AES256_GCM,data:ng/94rYMglg8Cw6+6J1rti7AAaQWgckpahlhn+4UAWd6Ff3Nt2QKLwOcHyaSStsKPStFqCAq3wU49brJ5xi3+hXHFFw3XasE52yZah756cjkAWiqu/JiCEFG9B8M8rBF/1O2HwGpj/TBH4NEf8JOrwg0vel882aoAN4kLf78zYA=,iv:XXxc1yGLR2k09QoqZbLQM/Rv0zrYCzRN8RgBNafpzBc=,tag:KtBHLZ9xC1SWdtaHBiqlsw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
