---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backup-credentials-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: backup-credentials
    template:
      engineVersion: v2
      data:
        CF_S3_ENDPOINT: "{{ .CF_S3_ENDPOINT }}"
        CF_ACCESS_KEY_ID: "{{ .CF_ACCESS_KEY_ID }}"
        CF_SECRET_ACCESS_KEY: "{{ .CF_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: secrets/cloudflare
