---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-pv
  namespace: bazarr
spec:
  storageClassName: data-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.${PUBLIC_DOMAIN}
    path: /mnt/exos20/data
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
