version: 1
metadata:
  name: Flow - Authentication
entries:
- model: authentik_blueprints.metaapplyblueprint
    attrs:
      identifiers:
        name: Identification Stage
      required: true

- model: authentik_blueprints.metaapplyblueprint
    attrs:
      identifiers:
        name: Authenticator Validator Stage
      required: true

- model: authentik_blueprints.metaapplyblueprint
    attrs:
      identifiers:
        name: User Login Stage
      required: true
- attrs:
    designation: authentication
    name: Welcome to authentik!
    title: Welcome to authentik!
    authentication: require_unauthenticated
    denied_action: continue
  identifiers:
    slug: 4bfe9942-e4b8-4096-99e8-4ac273d51737
  model: authentik_flows.flow
  id: flow
- identifiers:
    order: 100
    stage: !Find [authentik_stages_identification.identificationstage, [name, identification-stage]]
    target: !KeyOf flow
  model: authentik_flows.flowstagebinding
- identifiers:
    order: 200
    stage: !Find [authentik_stages_authenticator_validate.authenticatorvalidatestage, [name, authenticator-validation-stage]]
    target: !KeyOf flow
  model: authentik_flows.flowstagebinding
- identifiers:
    order: 900
    stage: !Find [authentik_stages_user_login.userloginstage, [name, user-login-stage]]
    target: !KeyOf flow
  model: authentik_flows.flowstagebinding
