# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Authenticator Validator Stage
entries:
- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Flow - TOTP Authenticator Setup
  attrs:
    required: true

- model: authentik_stages_authenticator_validate.authenticatorvalidatestage
  id: default-authenticator-validator-stage
  identifiers:
    name: default-authenticator-validator-stage
  attrs:
    last_auth_threshold: minutes=5
    not_configured_action: skip
    configuration_stages:
      - totp-authenticator-setup-stage
    device_classes:
      - totp
