# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Flow - Authentication
context:
  name: Welcome to authentik!
  title: Welcome to authentik!
entries:

- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Identification Stage
  attrs:
    required: true

- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Authenticator Validator Stage
  attrs:
    required: true

- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: User Login Stage
  attrs:
    required: true

- model: authentik_flows.flow
  id: flow
  identifiers:
    slug: 20ce7198-2240-42c4-a07a-dc51aa80b1b3
  attrs:
    authentication: require_unauthenticated
    denied_action: continue
    designation: authentication
    name: !Context name
    title: !Context title

- model: authentik_flows.flowstagebinding
  identifiers:
    target: !KeyOf flow
    stage: !Find [authentik_stages_identification.identificationstage, [name, identification-stage]]
  attrs:
    order: 100

- model: authentik_flows.flowstagebinding
  identifiers:
    target: !KeyOf flow
    stage: !Find [authentik_stages_authenticator_validate.authenticatorvalidatestage, [name, authenticator-validator-stage]]
  attrs:
    order: 200

- model: authentik_flows.flowstagebinding
  identifiers:
    target: !KeyOf flow
    stage: !Find [authentik_stages_user_login.userloginstage, [name, user-login-stage]]
  attrs:
    order: 900
