version: 1
metadata:
  name: Brand - Default
context:
    fqdn: ${PUBLIC_DOMAIN}
    branding_title: DarkfellaNET
entries:
- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Flow - Authentication
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Flow - Invalidation
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Flow - User Settings
    required: true

- model: authentik_brands.brand
  identifiers:
    default: true
  attrs:
    domain: !Context fqdn
    branding_title: !Context branding_title
    flow_authentication: !Find [authentik_flows.flow, [slug, 20ce7198-2240-42c4-a07a-dc51aa80b1b3]]
    flow_invalidation: !Find [authentik_flows.flow, [slug, 3334e93f-90b8-4935-88c4-a7ab8335efeb]]
    flow_user_settings: !Find [authentik_flows.flow, [slug, 02d14ae0-6b63-41c7-89b5-5eb145475888]]
