# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Expression Policy - Validate email Context Attribute Is Different Than Currently Set
entries:
- model: authentik_policies_expression.expressionpolicy
  id: validate-email-context-attribute-is-different-than-currently-set-expression-policy
  identifiers:
    name: validate-email-context-attribute-is-different-than-currently-set-expression-policy
  attrs:
    expression:  |
      email = request.context.get("prompt_data", {}).get("email", "")
      return request.user.email != email
