version: 1
metadata:
  name: Flow - Default Authentication
context:
  name: Sign In
  title: DarkfellaNET - Sign In
entries:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Identification Stage - Default
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Authenticator Validator Stage - Default
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: User Login Stage - Default
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Captcha Stage
    required: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_policies_reputation.reputationpolicy
  id: default-authentication-flow-conditional-captcha
  identifiers:
    name: default-authentication-flow-conditional-captcha
  attrs:
    check_ip: true
    check_username: true
    threshold: -5
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_flows.flow
  id: flow
  identifiers:
    slug: 7096c3cf-0416-41e5-b1b0-c4581079cb99
  attrs:
    authentication: require_unauthenticated
    denied_action: continue
    designation: authentication
    name: !Context name
    title: !Context title
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_flows.flowstagebinding
  identifiers:
    target: !KeyOf flow
    stage: !Find [authentik_stages_identification.identificationstage, [name, default-identification-stage]]
  attrs:
    order: 100

- model: authentik_flows.flowstagebinding
  id: flow-binding-captcha
  identifiers:
    target: !KeyOf flow
    stage: !Find [authentik_stages_captcha.captchastage, [name, captcha-stage]]
  attrs:
    order: 110

- model: authentik_flows.flowstagebinding
  identifiers:
    target: !KeyOf flow
    stage: !Find [authentik_stages_authenticator_validate.authenticatorvalidatestage, [name, default-authenticator-validator-stage]]
  attrs:
    order: 200

- model: authentik_flows.flowstagebinding
  identifiers:
    target: !KeyOf flow
    stage: !Find [authentik_stages_user_login.userloginstage, [name, default-user-login-stage]]
  attrs:
    order: 900
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_policies.policybinding
  identifiers:
    policy: !KeyOf default-authentication-flow-conditional-captcha
    target: !KeyOf flow-binding-captcha
    order: 0
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
