version: 1
metadata:
  name: Flow - Default Password Change
context:
  name: Change password
  title: Change password
  validate_current_password: true
entries:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_blueprints.metaapplyblueprint
  conditions:
  - !Context validate_current_password
  attrs:
    identifiers:
      name: Prompt Stage - Current Password
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Prompt Stage - Password and Password Repeat
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: User Write Stage - Default
    required: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_flows.flow
  id: flow
  identifiers:
    slug: 8d07df98-c696-42c3-95e0-8cc163dc5ab3
  attrs:
    authentication: require_authenticated
    denied_action: continue
    designation: stage_configuration
    name: !Context name
    title: !Context title
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_flows.flowstagebinding
  state: !If [!Context validate_current_password, present, absent]
  identifiers:
    stage: !Find [authentik_stages_prompt.promptstage, [name, current-password-prompt-stage]]
    target: !KeyOf flow
  attrs:
    order: 100

- model: authentik_flows.flowstagebinding
  identifiers:
    stage: !Find [authentik_stages_prompt.promptstage, [name, password-and-password-repeat-prompt-stage]]
    target: !KeyOf flow
  attrs:
    order: 200

- model: authentik_flows.flowstagebinding
  identifiers:
    stage: !Find [authentik_stages_user_write.userwritestage, [name, default-user-write-stage]]
    target: !KeyOf flow
  attrs:
    order: 900
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
