version: 1
metadata:
  name: Flow - Recovery Authenticator Setup
context:
  token_count: 1
  name: Configure Recovery Authenticator
  title: Configure Recovery Authenticator
  validate_current_password: true
entries:
- model: authentik_blueprints.metaapplyblueprint
  conditions:
  - !Context validate_current_password
  attrs:
    identifiers:
      name: Prompt Stage - Current Password
    required: true

- model: authentik_flows.flow
  id: flow
  identifiers:
    slug: 992fd499-f119-4eac-8f98-aca4d283ebeb
  attrs:
    authentication: require_authenticated
    denied_action: continue
    designation: stage_configuration
    name: !Context name
    title: !Context title

- model: authentik_stages_authenticator_static.authenticatorstaticstage
  id: recovery-authenticator-setup-stage
  identifiers:
    name: recovery-authenticator-setup-stage
  attrs:
    token_count: !Context token_count
    configure_flow: !KeyOf flow

- model: authentik_flows.flowstagebinding
  state: !If [!Context validate_current_password, present, absent]
  identifiers:
    stage: !Find [authentik_stages_prompt.promptstage, [name, current-password-prompt-stage]]
    target: !KeyOf flow
  attrs:
    order: 100

- model: authentik_flows.flowstagebinding
  identifiers:
    stage: !KeyOf recovery-authenticator-setup-stage
    target: !KeyOf flow
  attrs:
    order: 200
