# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Flow - Password Change
context:
  name: Change password
  title: Change password
  validate_current_password: true
entries:
- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Prompt Stage - Current Password
  conditions:
  - !Context validate_current_password
  attrs:
    required: true

- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Prompt Stage - Password and Password Repeat
  attrs:
    required: true

- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: User Write Stage
  attrs:
    required: true

- model: authentik_flows.flow
  id: flow
  identifiers:
    slug: 6ef43887-af21-4247-8bbf-d69e79e27e3c
  attrs:
    authentication: require_authenticated
    denied_action: continue
    designation: stage_configuration
    name: !Context name
    title: !Context title

- model: authentik_flows.flowstagebinding
  state: !If [!Context validate_current_password, present, absent]
  identifiers:
    stage: !Find [authentik_stages_prompt.promptstage, [name, current-password-prompt-stage]]
    target: !KeyOf flow
  attrs:
    order: 100

- model: authentik_flows.flowstagebinding
  identifiers:
    stage: !Find [authentik_stages_prompt.promptstage, [name, password-and-password-repeat-prompt-stage]]
    target: !KeyOf flow
  attrs:
    order: 200

- model: authentik_flows.flowstagebinding
  identifiers:
    stage: !Find [authentik_stages_user_write.userwritestage, [name, user-write-stage]]
    target: !KeyOf flow
  attrs:
    order: 900
