# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Identification Stage - Recovery
context:
  show_matched_user: false
  user_fields:
  - email
  - username
entries:
- model: authentik_stages_identification.identificationstage
  id: recovery-identification-stage
  identifiers:
    name: recovery-identification-stage
  attrs:
    user_fields: !Context user_fields
    show_matched_user: !Context show_matched_user
