# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Notification Rule - Update Available
context:
  group_name: null
  notify_email: true
  notify_local: true
entries:

- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Notification Transport - Email
  attrs:
    required: true

- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Notification Transport - Local
  attrs:
    required: true

- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Event Matcher Policy - Update Available
  attrs:
    required: true

- model: authentik_events.notificationrule
  id: update-available-notification-rule
  identifiers:
    name: update-available-notification-rule
  attrs:
    severity: alert
    group: !If [
      !Condition [OR, !Context notify_email, !Context notify_local],
      !If [
        !Context group_name,
        !Find [authentik_core.group, [name, !Context group_name]],
        !Find [authentik_core.group, [attributes__contains, {better-blueprints/id: default-admins-group}]]
      ],
      null
    ]
    transports: !If [
      !Condition [AND, !Context notify_email, !Context notify_local],
      [
        !Find [authentik_events.notificationtransport, [name, email-notification-transport]],
        !Find [authentik_events.notificationtransport, [name, local-notification-transport]]
      ],
      !If [
        !Context notify_email,
        [
          !Find [authentik_events.notificationtransport, [name, email-notification-transport]]
        ],
        !If [
          !Context notify_local,
          [
            !Find [authentik_events.notificationtransport, [name, local-notification-transport]]
          ],
          []
        ]
      ]
    ]

- model: authentik_policies.policybinding
  identifiers:
    policy: !Find [authentik_policies_event_matcher.eventmatcherpolicy, [name, update-available-event-matcher-policy]]
    target: !KeyOf update-available-notification-rule
  attrs:
    order: 100
    enabled: true
    timeout: 30
