version: 1
metadata:
  name: Password Policy - Secure
entries:
- model: authentik_policies_password.passwordpolicy
  id: secure-password-policy
  identifiers:
    name: secure-password-policy
  attrs:
    password_field: password
    check_have_i_been_pwned: true
    hibp_allowed_count: 1
    check_zxcvbn: true
    zxcvbn_score_threshold: 3
    check_static_rules: true
    amount_digits: 1
    amount_uppercase: 1
    amount_lowercase: 1
    amount_symbols: 1
    length_min: 12
    symbol_charset: >-
      !\"#$%&'()*+,-./:;<=>?@[]^_`{|}~
    error_message: >-
      Passwords must consist of minimum 12 characters, at least one uppercase
      letter, at least one lowercase letter, at least one digit and at least
      one special character
