# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Password Policy - Default
entries:
- model: authentik_policies_password.passwordpolicy
  id: default-password-policy
  identifiers:
    name: default-password-policy
  attrs:
    password_field: password
    amount_digits: 0
    amount_uppercase: 1
    amount_lowercase: 1
    amount_symbols: 1
    length_min: 10
    symbol_charset: >-
      !\"#$%&'()*+,-./:;<=>?@[]^_`{|}~0123456789
    error_message: >-
      Passwords must consist of minimum 10 characters, at least one uppercase
      letter, at least one lowercase letter and at least one digit or special
      character
    check_static_rules: true
    check_have_i_been_pwned: true
    check_zxcvbn: true
    hibp_allowed_count: 1
    zxcvbn_score_threshold: 3
