# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Prompt Stage - Current Password
entries:
- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Prompt - current_password
  attrs:
    required: true

- model: authentik_blueprints.metaapplyblueprint
  identifiers:
      name: Expression Policy - Validate current_password Context Attribute Matches User Password
  attrs:
    required: true

- model: authentik_stages_prompt.promptstage
  id: current-password-prompt-stage
  identifiers:
    name: current-password-prompt-stage
  attrs:
    fields:
    - !Find [authentik_stages_prompt.prompt, [field_key, current_password]]
    validation_policies:
    - !Find [authentik_policies_expression.expressionpolicy, [name, validate-current_password-context-attribute-matches-user-password-expression-policy]]
