# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Prompt - first_name and last_name
entries:
- model: authentik_stages_prompt.prompt
  id: first-name-prompt
  identifiers:
    name: first-name-prompt
    field_key: first_name
    label: First name
  attrs:
    order: 110
    placeholder: |
      try:
          return user.name.split(" ")[0]
      except:
          return 'First name'
    placeholder_expression: true
    required: true
    type: text

- model: authentik_stages_prompt.prompt
  id: last-name-prompt
  identifiers:
    name: last-name-prompt
    field_key: last_name
    label: Last name
  attrs:
    order: 120
    placeholder: |
      try:
          return user.name.split(" ")[-1]
      except:
          return 'Last name'
    placeholder_expression: true
    required: true
    type: text
