# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Prompt - email
entries:
- model: authentik_stages_prompt.prompt
  id: email-prompt
  identifiers:
    name: email-prompt
    field_key: email
    label: Email
  attrs:
    order: 310
    placeholder: |
      try:
          return user.email
      except:
          return 'Email'
    placeholder_expression: true
    required: true
    type: email
