# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: Prompt - attributes.settings.locale
entries:
- model: authentik_stages_prompt.prompt
  id: attributes-settings-locale-prompt
  identifiers:
    name: attributes-settings-locale-prompt
    field_key: attributes.settings.locale
    label: Locale
  attrs:
    order: 410
    placeholder: |
      try:
          return user.attributes.get("settings", {}).get("locale", "")
      except:
          return ''
    placeholder_expression: true
    required: true
    type: ak-locale
