version: 1
    metadata:
      name: Flow - TOTP Authenticator Setup
    context:
      digits: 6
      name: Configure TOTP Authenticator
      title: Configure TOTP Authenticator
      validate_current_password: true
    entries:
    - model: authentik_blueprints.metaapplyblueprint
      conditions:
      - !Context validate_current_password
      attrs:
        identifiers:
          name: Prompt Stage - Current Password
        required: true
    - model: authentik_flows.flow
      id: flow
      identifiers:
        slug: 59f5668b-24fe-4cc4-a11b-a65bc5414b56
      attrs:
        authentication: require_authenticated
        denied_action: continue
        designation: stage_configuration
        name: !Context name
        title: !Context title
    - model: authentik_stages_authenticator_totp.authenticatortotpstage
      id: totp-authenticator-setup-stage
      identifiers:
        name: totp-authenticator-setup-stage
      attrs:
        digits: !Context digits
        configure_flow: !KeyOf flow
    - model: authentik_flows.flowstagebinding
      state: !If [!Context validate_current_password, present, absent]
      identifiers:
        stage: !Find [authentik_stages_prompt.promptstage, [name, current-password-prompt-stage]]
        target: !KeyOf flow
      attrs:
        order: 100
    - model: authentik_flows.flowstagebinding
      identifiers:
        stage: !KeyOf totp-authenticator-setup-stage
        target: !KeyOf flow
      attrs:
        order: 200
