# yaml-language-server: $schema=https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/blueprints/schema.json
version: 1
metadata:
  name: User Login Stage
entries:
- model: authentik_stages_user_login.userloginstage
  id: user-login-stage
  identifiers:
    name: user-login-stage
  attrs:
    session_duration: seconds=0
