version: 1
metadata:
  name: User Write Stage
entries:
- model: authentik_stages_user_write.userwritestage
  id: user-write-stage
  identifiers:
    name: user-write-stage
  attrs:
    can_create_users: false
