endpoints:
  - name: "qBittorrent"
    group: guarded
    url: "https://qbittorrent.darkfellanetwork.com/api/v2/app/version"
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[STATUS] == 403"
    alerts:
      - type: pushover
    headers:
      Accept: application/json
