---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: theme-park
spec:
  interval: 30m
  chart:
    spec:
      chart: theme-park
      version: 11.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    securityContext:
      container:
        readOnlyRootFilesystem: true
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
          kubernetes.io/ingress.class: external
        hosts:
          - host: &host theme-park.${PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
        integrations:
          traefik:
            enabled: false
