---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./virtualmachine.yaml
  - https://github.com/kubevirt/kubevirt-tekton-tasks/releases/download/v0.23.0/kubevirt-tekton-tasks.yaml
  - ./tekton-sa-rbac.yaml
