---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-vm
  namespace: virtualization
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-vm-from-manifest
  namespace: virtualization
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: disk-uploader
  namespace: virtualization
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: disk-virt-customize
  namespace: virtualization
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: disk-virt-sysprep
  namespace: virtualization
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: execute-in-vm
  namespace: virtualization
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-ssh-keys
  namespace: virtualization
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: modify-data-object
  namespace: virtualization
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: modify-windows-iso-file
  namespace: virtualization
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-vmi-status
  namespace: virtualization
