apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows2k25-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26100.1742.240906-0331.ge_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso
    - name: acceptEula
      value: true
    - name: preferenceName
      value: windows.2k25.virtio
    - name: autounattendConfigMapName
      value: windows2k25-autounattend
    - name: baseDvName
      value: win2k25
    - name: isoDVName
      value: win2k25
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: kubevirt-tekton-pipelines
      - name: type
        value: artifact
      - name: kind
        value: pipeline
      - name: name
        value: windows-efi-installer
      - name: version
        value: v0.23.0
  taskRunTemplate:
    serviceAccountName: custom-pipelinerun-sa
  taskRunSpecs:
    - pipelineTaskName: modify-windows-iso-file
      podTemplate:
        securityContext:
          fsGroup: 107
          runAsUser: 107
  timeouts:
    pipeline: 1h0m0s
