---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-pipelinerun-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-pipelinerun-sa-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["delete", "get", "create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "delete", "update"]
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes", "datasources"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines", "virtualmachineinstances"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["subresources.kubevirt.io"]
    resources: ["virtualmachines/start", "virtualmachines/stop", "virtualmachines/restart"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-pipelinerun-sa-rolebinding
subjects:
  - kind: ServiceAccount
    name: custom-pipelinerun-sa
    namespace: virtualization
roleRef:
  kind: Role
  name: custom-pipelinerun-sa-role
  apiGroup: rbac.authorization.k8s.io
