---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./authentik.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./crowdsec.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./descheduler.yaml
  - ./emberstack.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./vaultwarden.yaml
  - ./grafana.yaml
  - ./jetstack.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./topolvm.yaml
  - ./truecharts.yaml
  - ./nvidia-device-plugin.yaml
  - ./ingress-nginx.yaml
  - ./vault.yaml
