apiVersion: v1
kind: ConfigMap
metadata:
  name: rules
data:
  configuration-error.yaml: |
    version: 1
    metadata:
      name: Notification Rule - Configuration Error
    context:
      severity: alert
      group_name: null
      notify_email: true
      notify_local: true
    entries:
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_blueprints.metaapplyblueprint
      conditions:
      - !Context notify_email
      attrs:
        identifiers:
          name: Notification Transport - Email
        required: true

    - model: authentik_blueprints.metaapplyblueprint
      conditions:
      - !Context notify_local
      attrs:
        identifiers:
          name: Notification Transport - Local
        required: true

    - model: authentik_blueprints.metaapplyblueprint
      attrs:
        identifiers:
          name: Event Matcher Policy - Configuration Error
        required: true
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_events.notificationrule
      id: configuration-error-notification-rule
      identifiers:
        name: configuration-error-notification-rule
      attrs:
        severity: !Context severity
        group: !If [
          !Condition [OR, !Context notify_email, !Context notify_local],
          !If [
            !Context group_name,
            !Find [authentik_core.group, [name, !Context group_name]],
            !Find [authentik_core.group, [attributes__contains, {better-blueprints/id: default-admins-group}]]
          ],
          null
        ]
        transports: !If [
          !Condition [AND, !Context notify_email, !Context notify_local],
          [
            !Find [authentik_events.notificationtransport, [name, email-notification-transport]],
            !Find [authentik_events.notificationtransport, [name, local-notification-transport]]
          ],
          !If [
            !Context notify_email,
            [
              !Find [authentik_events.notificationtransport, [name, email-notification-transport]]
            ],
            !If [
              !Context notify_local,
              [
                !Find [authentik_events.notificationtransport, [name, local-notification-transport]]
              ],
              []
            ]
          ]
        ]
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_policies.policybinding
      identifiers:
        policy: !Find [authentik_policies_event_matcher.eventmatcherpolicy, [name, configuration-error-event-matcher-policy]]
        target: !KeyOf configuration-error-notification-rule
      attrs:
        order: 100
        enabled: true
        timeout: 30
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  exceptions.yaml: |
    version: 1
    metadata:
      name: Notification Rule - Exceptions
    context:
      severity: alert
      group_name: null
      notify_email: true
      notify_local: true
    entries:
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_blueprints.metaapplyblueprint
      conditions:
      - !Context notify_email
      attrs:
        identifiers:
          name: Notification Transport - Email
        required: true

    - model: authentik_blueprints.metaapplyblueprint
      conditions:
      - !Context notify_local
      attrs:
        identifiers:
          name: Notification Transport - Local
        required: true

    - model: authentik_blueprints.metaapplyblueprint
      attrs:
        identifiers:
          name: Event Matcher Policy - Policy Exception
        required: true

    - model: authentik_blueprints.metaapplyblueprint
      attrs:
        identifiers:
          name: Event Matcher Policy - Property Mapping Exception
        required: true
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_events.notificationrule
      id: exceptions-notification-rule
      identifiers:
        name: exceptions-notification-rule
      attrs:
        severity: !Context severity
        group: !If [
          !Condition [OR, !Context notify_email, !Context notify_local],
          !If [
            !Context group_name,
            !Find [authentik_core.group, [name, !Context group_name]],
            !Find [authentik_core.group, [attributes__contains, {better-blueprints/id: default-admins-group}]]
          ],
          null
        ]
        transports: !If [
          !Condition [AND, !Context notify_email, !Context notify_local],
          [
            !Find [authentik_events.notificationtransport, [name, email-notification-transport]],
            !Find [authentik_events.notificationtransport, [name, local-notification-transport]]
          ],
          !If [
            !Context notify_email,
            [
              !Find [authentik_events.notificationtransport, [name, email-notification-transport]]
            ],
            !If [
              !Context notify_local,
              [
                !Find [authentik_events.notificationtransport, [name, local-notification-transport]]
              ],
              []
            ]
          ]
        ]
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_policies.policybinding
      identifiers:
        policy: !Find [authentik_policies_event_matcher.eventmatcherpolicy, [name, policy-exception-event-matcher-policy]]
        target: !KeyOf exceptions-notification-rule
      attrs:
        order: 100
        enabled: true
        timeout: 30

    - model: authentik_policies.policybinding
      identifiers:
        policy: !Find [authentik_policies_event_matcher.eventmatcherpolicy, [name, property-mapping-exception-event-matcher-policy]]
        target: !KeyOf exceptions-notification-rule
      attrs:
        order: 200
        enabled: true
        timeout: 30
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  update-available.yaml: |
    version: 1
    metadata:
      name: Notification Rule - Update Available
    context:
      severity: alert
      group_name: null
      notify_email: true
      notify_local: true
    entries:
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_blueprints.metaapplyblueprint
      conditions:
      - !Context notify_email
      attrs:
        identifiers:
          name: Notification Transport - Email
        required: true

    - model: authentik_blueprints.metaapplyblueprint
      conditions:
      - !Context notify_local
      attrs:
        identifiers:
          name: Notification Transport - Local
        required: true

    - model: authentik_blueprints.metaapplyblueprint
      attrs:
        identifiers:
          name: Event Matcher Policy - Update Available
        required: true
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_events.notificationrule
      id: update-available-notification-rule
      identifiers:
        name: update-available-notification-rule
      attrs:
        severity: !Context severity
        group: !If [
          !Condition [OR, !Context notify_email, !Context notify_local],
          !If [
            !Context group_name,
            !Find [authentik_core.group, [name, !Context group_name]],
            !Find [authentik_core.group, [attributes__contains, {better-blueprints/id: default-admins-group}]]
          ],
          null
        ]
        transports: !If [
          !Condition [AND, !Context notify_email, !Context notify_local],
          [
            !Find [authentik_events.notificationtransport, [name, email-notification-transport]],
            !Find [authentik_events.notificationtransport, [name, local-notification-transport]]
          ],
          !If [
            !Context notify_email,
            [
              !Find [authentik_events.notificationtransport, [name, email-notification-transport]]
            ],
            !If [
              !Context notify_local,
              [
                !Find [authentik_events.notificationtransport, [name, local-notification-transport]]
              ],
              []
            ]
          ]
        ]
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_policies.policybinding
      identifiers:
        policy: !Find [authentik_policies_event_matcher.eventmatcherpolicy, [name, update-available-event-matcher-policy]]
        target: !KeyOf update-available-notification-rule
      attrs:
        order: 100
        enabled: true
        timeout: 30
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
