apiVersion: v1
kind: ConfigMap
metadata:
  name: tenants
data:
  default.yaml: |
    version: 1
    metadata:
      name: Tenant - Default
    context:
        fqdn: authentik - default
        branding_title: authentik
    entries:
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_blueprints.metaapplyblueprint
      attrs:
        identifiers:
          name: Flow - Default Authentication
        required: true

    - model: authentik_blueprints.metaapplyblueprint
      attrs:
        identifiers:
          name: Flow - Default Invalidation
        required: true

    - model: authentik_blueprints.metaapplyblueprint
      attrs:
        identifiers:
          name: Flow - Default User Settings
        required: true
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    - model: authentik_brands.brand
      identifiers:
        default: True
      attrs:
        domain: !Context fqdn
        branding_title: !Context branding_title
        flow_authentication: !Find [authentik_flows.flow, [slug, 4bfe9942-e4b8-4096-99e8-4ac273d51737]]
        flow_invalidation: !Find [authentik_flows.flow, [slug, 3334e93f-90b8-4935-88c4-a7ab8335efeb]]
        flow_user_settings: !Find [authentik_flows.flow, [slug, 02d14ae0-6b63-41c7-89b5-5eb145475888]]
