---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
spec:
  configuration:
    vmStateStorageClass: "openebs-zfs-128k"
    developerConfiguration:
      featureGates:
        - HostDevices
        - DataVolumes
        - VMPersistentState
        - ExpandDisks
    permittedHostDevices:
      pciHostDevices:
        - pciVendorSelector: 1000:0097
          resourceName: devices.kubevirt.io/sas
        - pciVendorSelector: 8086:2701
          resourceName: devices.kubevirt.io/nvme
