---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-1m
allowVolumeExpansion: true
parameters:
  thinprovision: "yes"
  recordsize: "1m"
  compression: "lz4"
  dedup: "off"
  fstype: "zfs"
  shared: "yes"
  poolname: "ssd_pool"
provisioner: zfs.csi.openebs.io

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-128k
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  thinprovision: "yes"
  recordsize: "128k"
  compression: "lz4"
  dedup: "off"
  fstype: "zfs"
  shared: "yes"
  poolname: "ssd_pool"
provisioner: zfs.csi.openebs.io
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-32k
allowVolumeExpansion: true
parameters:
  thinprovision: "yes"
  recordsize: "32k"
  compression: "lz4"
  dedup: "off"
  fstype: "zfs"
  shared: "yes"
  poolname: "ssd_pool"
provisioner: zfs.csi.openebs.io
