apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-server-2022
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows-server-2022
    spec:
      networks:
        - name: bridge
          multus:
            default: true
            networkName: kube-system/bridge-windows-server
      domain:
        cpu:
          cores: 2
          model: host-passthrough
        features:
          acpi: {}
          apic: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
          uuid: 43a838b8-9c2f-41ef-84b0-2370fd097a97
        devices:
          interfaces:
            - name: bridge
              bridge: {}
              model: virtio
              macAddress: 1e:f5:6e:08:1f:59
          tpm: {}
          disks:
            #- cdrom:
                #bus: sata
              #name: windows-server-iso
            - disk:
                bus: virtio
              name: windows-server-os-disk
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
      volumes:
      #- name: windows-server-iso
        #persistentVolumeClaim:
          #claimName: windows-server-iso
      - name: windows-server-os-disk
        persistentVolumeClaim:
          claimName: windows-server-os-disk
