---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-receiver
  annotations:
    external-dns.alpha.kubernetes.io/target: external.${PUBLIC_DOMAIN}
    kubernetes.io/ingress.class: external
spec:
  tls:
    - hosts:
        - &host flux-webhook.${PUBLIC_DOMAIN}
  rules:
    - host: *host
      http:
        paths:
          - path: /hook/
            pathType: Prefix
            backend:
              service:
                name: webhook-receiver
                port:
                  number: 80
