---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webhook-receiver
  annotations:
    kubernetes.io/ingress.class: external
    external-dns.alpha.kubernetes.io/target: ${PUBLIC_DOMAIN}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flux-webhook.${PUBLIC_DOMAIN}`) && PathPrefix(`/hook/`)
      kind: Rule
      services:
        - name: webhook-receiver
          port: 80
      middlewares:
        - name: bouncer
          namespace: networking
        - name: realip
          namespace: networking
