apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/exos20/owasp-modsecurity-crs
    server: nas.${PUBLIC_DOMAIN}
  persistentVolumeReclaimPolicy: Retain
