SecAction \
    "id:900200,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    tag:'OWASP_CRS',\
    ver:'OWASP_CRS/4.4.0',\
    setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE PATCH'"
