image:
  repository: darkfella/lvm-disk-watcher
  pullPolicy: IfNotPresent
  tag: v0.20.0
configmap:
  disk-config:
    enabled: true
    data:
      disk-config: |
        k8s-0: /dev/sdb /dev/sdc /dev/s
securityContext:
  container:
    readOnlyRootFilesystem: false
