---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "vaultwarden-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "vaultwarden"
        group: external
        url: "https://vaultwarden.${PUBLIC_DOMAIN}/alive"
        interval: 30s
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
          - "[BODY] == pat('.*T.*Z')"
        alerts:
          - type: pushover
