endpoints:
  - name: "Vaultwarden"
    group: external
    url: "https://vaultwarden.${PUBLIC_DOMAIN}/alive"
    interval: 5m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
