---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret qbittorrent-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"
        PUSHOVER_TOKEN: "{{ .QBITTORRENT_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
        CLIENT_SECRET: "{{ .CLIENT_SECRET}}"
        CLIENT_ID: "{{ .CLIENT_ID }}"
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            delay: 30,
            duplicateCategories: false,
            flatLinking: false,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkCategory: "cross-seed",
            linkDir: "/data/downloads/torrents/complete/cross-seed",
            linkType: "hardlink",
            matchMode: "safe",
            outputDir: "/config",
            port: 8080,
            qbittorrentUrl: "http://{{ .QBITTORRENT_USERNAME }}:{{ .QBITTORRENT_PASSWORD }}@localhost",
            radarr: ["https://radarr.darkfellanetwork.com/?apikey={{ .RADARR_API_KEY }}"],
            skipRecheck: true,
            sonarr: ["https://sonarr.darkfellanetwork.com/?apikey={{ .SONARR_API_KEY }}"],
            torrentDir: "/qbittorrent/qBittorrent/BT_backup",
            torznab: [
                3, // IPT
                1, // SA
                2, // TL
            ].map(i => `https://prowlarr.darkfellanetwork.com/$${i}/api?apikey={{ .PROWLARR_API_KEY }}`),
          };
        config.yml: |
          commands:
            dry_run: false
            cross_seed: false
            recheck: false
            cat_update: false
            tag_update: true
            rem_unregistered: true
            tag_tracker_error: true
            rem_orphaned: true
            tag_nohardlinks: true
            share_limits: true
            skip_qb_version_check: true
            skip_cleanup: false

          qbt:
            host: localhost:80
            user: {{ .QBITTORRENT_USERNAME }}
            pass: {{ .QBITTORRENT_PASSWORD }}

          settings:
            force_auto_tmm: false
            tracker_error_tag: issue
            nohardlinks_tag: noHL
            share_limits_tag: ~share_limit
            share_limits_min_seeding_time_tag: MinSeedTimeNotReached
            share_limits_min_num_seeds_tag: MinSeedsNotMet
            share_limits_last_active_tag: LastActiveLimitNotReached
            cross_seed_tag: cross-seed
            cat_filter_completed: true
            share_limits_filter_completed: true
            tag_nohardlinks_filter_completed: true
            cat_update_all: true

            force_auto_tmm_ignore_tags: cross-seed
            disable_qbt_default_share_limits: true

          directory:
            remote_dir: /data/downloads/torrents
            cross_seed: /your/path/here/
            root_dir: /data/downloads/torrents
            recycle_bin: /data/downloads/torrents/.RecycleBin
            torrents_dir: /qBittorrent/BT_backup
            orphaned_dir: /data/downloads/torrents/orphaned_data

          cat:

          cat_change:

          tracker:
            torrentleech|tleechreload:
              tag: TorrentLeech
              notifiarr: torrentleech
            stackoverflow|empirehost|bgp:
              tag: IPTorrents
              notifiarr: iptorrents
            speedapp:
              tag: speedapp.io
              notifiarr: speedapp.io
            other:
              tag: other

          nohardlinks:
            movies:
              ignore_root_dir: true
            movies-imported:
              exclude_tags:
              - Beyond-HD
              - AnimeBytes
              - MaM
              ignore_root_dir: true
            tv:
              ignore_root_dir: true
            tv-imported:
              exclude_tags:
              - Beyond-HD
              - AnimeBytes
              - MaM
              ignore_root_dir: true
            cross-seed:
              ignore_root_dir: false

          share_limits:

            noHL_cross-seed:
              priority: 1
              include_all_tags:
              - noHL
              - cross-seed
              categories:
              - cross-seed
              max_seeding_time: 10m
              cleanup: true
              custom_tag: sharelimits_noHL_cross-seed
            noHL_TorrentLeech:
              priority: 2
              include_all_tags:
              - noHL
              - TorrentLeech
              categories:
              - movies
              - movies-imported
              - tv
              - tv-imported
              max_seeding_time: 10d
              cleanup: true
              resume_torrent_after_change: true
              add_group_to_tag: true
              custom_tag: sharelimits_noHL_TorrentLeech

            noHL_speedapp.io:
              priority: 3
              include_all_tags:
              - noHL
              - speedapp.io
              categories:
              - movies
              - movies-imported
              - tv
              - tv-imported
              max_seeding_time: 3d
              cleanup: true
              resume_torrent_after_change: true
              add_group_to_tag: true
              custom_tag: sharelimits_noHL_speedapp.io

            noHL_IPTorrents:
              priority: 4
              include_all_tags:
              - noHL
              - IPTorrents
              categories:
              - movies
              - movies-imported
              - tv
              - tv-imported
              max_seeding_time: 16d
              cleanup: true
              resume_torrent_after_change: true
              add_group_to_tag: true
              custom_tag: sharelimits_noHL_IPTorrents

            TorrentLeech:
              priority: 5
              include_all_tags:
              - TorrentLeech
              categories:
              - movies
              - movies-imported
              - tv
              - tv-imported
              - cross-seed
              max_seeding_time: 30d
              cleanup: true
              resume_torrent_after_change: true
              add_group_to_tag: true
              custom_tag: sharelimits_TorrentLeech

            IPTorrents:
              priority: 6
              include_all_tags:
              - IPTorrents
              categories:
              - movies
              - movies-imported
              - tv
              - tv-imported
              - cross-seed
              max_seeding_time: 30d
              cleanup: true
              resume_torrent_after_change: true
              add_group_to_tag: true
              custom_tag: sharelimits_IPTorrents

            speedapp.io:
              priority: 7
              include_all_tags:
              - speedapp.io
              categories:
              - movies
              - movies-imported
              - tv
              - tv-imported
              - cross-seed
              max_seeding_time: 30d
              cleanup: true
              resume_torrent_after_change: true
              add_group_to_tag: true
              custom_tag: sharelimits_speedapp.io

            general:
              priority: 8
              include_any_tags:
              - speedapp.io
              - IPTorrents
              - TorrentLeech
              categories:
              - general-completed
              max_ratio: 5
              max_seeding_time: 30d
              cleanup: false
              resume_torrent_after_change: true
              add_group_to_tag: true
              custom_tag: sharelimits_general

          recyclebin:
            enabled: true
            empty_after_x_days: 7
            save_torrents: true
            split_by_category: true

          orphaned:
            empty_after_x_days: 7
            exclude_patterns:
            - '**/.DS_Store'
            - '**/Thumbs.db'
            - '**/@eaDir'
            - '**/general/*'
            - '**/*.!qB'
            - '**/*_unpackerred'
            max_orphaned_files_to_delete: 50000

  dataFrom:
    - extract:
        key: secrets/api-keys
    - extract:
        key: secrets/pushover
    - extract:
        key: secrets/oauth2/qbittorrent
    - extract:
        key: secrets/redis
    - extract:
        key: secrets/qbittorrent
