---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  postRenderers:
    - kustomize:
        images:
          - name: tccr.io/tccr/gluetun
            newName: docker.io/qmcgaw/gluetun
            newTag: v3.39.1@sha256:6a8058e626763cbf735ac2f78c774dbb24fec2490bd9d9f7d67e22592cb4a991
        patches:
          - target:
              version: v1
              kind: Deployment
              name: qbittorrent
            patch: |
              - op: add
                path: /spec/template/spec/containers/1/resources/limits/squat.ai~1tun
                value: 1
              - op: add
                path: /spec/template/spec/containers/1/lifecycle
                value: {}
              - op: add
                path: /spec/template/spec/containers/1/lifecycle/postStart
                value: {}
              - op: add
                path: /spec/template/spec/containers/1/lifecycle/postStart/exec
                value: {}
              - op: add
                path: /spec/template/spec/containers/1/lifecycle/postStart/exec/command
                value:
                  - /bin/sh
                  - -c
                  - ip rule del table 51820; ip -6 rule del table 51820 || true
  interval: 30m
  chart:
    spec:
      chart: qbittorrent
      version: 22.1.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - targetPath: credentials.s3.url
      kind: Secret
      name: &secret volsync-backup-credentials
      valuesKey: CF_S3_ENDPOINT
    - targetPath: credentials.s3.encrKey
      kind: Secret
      name: *secret
      valuesKey: ENCRYPTION_KEY
    - targetPath: credentials.s3.accessKey
      kind: Secret
      name: *secret
      valuesKey: CF_ACCESS_KEY_ID
    - targetPath: credentials.s3.secretKey
      kind: Secret
      name: *secret
      valuesKey: CF_SECRET_ACCESS_KEY
  values:
    credentials:
      s3:
        type: s3
        bucket: backups
    persistence:
      config:
        size: 5Gi
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 5Gi
              enabled: true
            src:
              enabled: true
              cacheCapacity: 5Gi
      torrents:
        enabled: true
        type: nfs
        path: /mnt/exos20/data
        server: nas.${PUBLIC_DOMAIN}
        mountPath: /data/torrents
        subPath: torrents
      vuetorrent:
        enabled: true
        size: 1Gi
        mountPath: "/vuetorrent"
        volsync:
          - name: vuetorrent
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 1Gi
              enabled: false
            src:
              enabled: true
              cacheCapacity: 1Gi
    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - "192.168.91.0/24"
        excludedNetworks_IPv6: []
        env:
          VPN_SERVICE_PROVIDER: "protonvpn"
          VPN_TYPE: "wireguard"
          PORT_FORWARD_ONLY: "on"
          SERVER_CITIES: "Zurich"
          WIREGUARD_PRIVATE_KEY:
            secretKeyRef:
                    expandObjectName: false
                    name: protonvpn-credentials
                    key: PRIVATE_KEY
          VPN_PORT_FORWARDING: "on"
          VPN_PORT_FORWARDING_LISTENING_PORT: "6881"
          FIREWALL_DEBUG: "on"
          LOG_LEVEL: "debug"
          DNS_KEEP_NAMESERVER: "off"
          DOT: "on"
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${PUBLIC_DOMAIN}
          kubernetes.io/ingress.class: internal
        hosts:
          - host: &host qbittorrent.${PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
        integrations:
          traefik:
            enabled: false
