---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      verify:
        provider: cosign
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: volsync-system

  values:
    controllers:
      torrenting:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          oauth2-proxy:
            image:
              repository: quay.io/oauth2-proxy/oauth2-proxy
              tag: v7.7.1-amd64@sha256:95f2002754cb0f1c1553aed56f4d6564a5b860e01baccb4e1b8311ffa25c167c
            args:
              - --config=/etc/oauth2-proxy.cfg
            env:
              OAUTH2_PROXY_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: &secret qbittorrent-secret
                    key: CLIENT_ID
              OAUTH2_PROXY_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: CLIENT_SECRET
              OAUTH2_PROXY_COOKIE_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: COOKIE_SECRET
              OAUTH2_PROXY_REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: REDIS_PASSWORD
              OAUTH2_PROXY_SESSION_STORE_TYPE: redis
              OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis-master.database.svc.cluster.local:6379/9
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              runAsUser: 2000
              runAsGroup: 2000

          qbittorrent:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.3@sha256:025f32d260a3e924885405c0ca01ab8e396360330438ef8562ffd973d2dbb927
            env:
              UMASK: "022"
              TZ: &TZ Europe/Sofia
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 50413
              CROSS_SEED_ENABLED: true
              CROSS_SEED_HOST: localhost
              CROSS_SEED_PORT: 8080
              CROSS_SEED_SLEEP_INTERVAL: 15
              PUSHOVER_ENABLED: true
              CROSS_SEED_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: CROSS_SEED_API_KEY
              PUSHOVER_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: PUSHOVER_TOKEN
              PUSHOVER_USER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: PUSHOVER_USER_KEY
            probes:
              readiness:
                enabled: false
                custom: true
                spec:
                  exec:
                    command:
                      - /scripts/healthcheck.sh
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  failureThreshold: 3
              liveness:
                enabled: false
                custom: true
                spec:
                  exec:
                    command:
                      - /scripts/healthcheck.sh
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  failureThreshold: 3
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 16Gi

          qbitmanage:
            dependsOn: qbittorrent
            image:
              repository: ghcr.io/stuffanthings/qbit_manage
              tag: v4.1.14@sha256:a64f0781aabe3e66a261c8b21b7192555bc785f178cae40c6e8b88bf9b853c16
            env:
              TZ: *TZ
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: false
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 8Gi
            lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "cp /secret/config.yml /config/config.yml"]

          cross-seed:
            dependsOn: qbittorrent
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 6.2.3@sha256:22184878995cd3ea7027ec2045aec0323f43621135f51747ca00adfc17e6d01f
            env:
              TZ: *TZ
            args: ["daemon"]
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

          vuetorrent:
            dependsOn: qbittorrent
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.4.0
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --root=/addons
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 25Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    terminationGracePeriodSeconds: 300

    service:
      qbittorrent:
        controller: torrenting
        type: LoadBalancer
        allocateLoadBalancerNodePorts: false
        annotations:
          lbipam.cilium.io/ips: 192.168.91.82
        ports:
          http:
            port: 4180
          bittorrent-tcp:
            enabled: true
            port: *torrentPort
            protocol: TCP
          bittorrent-udp:
            enabled: true
            port: *torrentPort
            protocol: UDP

    ingress:
      qbittorrent:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${PUBLIC_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</body>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/vuetorrent/mind.css"></body>';
            sub_filter_once on;
          cert-manager.io/cluster-issuer: zerossl-prod
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
        className: internal
        tls:
          - hosts:
              - &host "{{ .Release.Name }}.${PUBLIC_DOMAIN}"
            secretName: qbittorrent-tls
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: qbittorrent
                  port: http

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        storageClass: openebs-zfs-128k
        advancedMounts:
          torrenting:
            qbittorrent:
              - path: /config
            qbitmanage:
              - path: /qBittorrent/BT_backup
                subPath: qBittorrent/BT_backup
                readOnly: true
            cross-seed:
              - path: /qbittorrent/qBittorrent/BT_backup
                subPath: qBittorrent/BT_backup
                readOnly: true

      scripts:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0550
        advancedMounts:
          torrenting:
            qbittorrent:
              - readOnly: true

      media:
        type: nfs
        server: 192.168.91.40
        path: /mnt/exos20/data
        advancedMounts:
          torrenting:
            qbitmanage:
              - path: /data/downloads/torrents
                subPath: downloads/torrents
            qbittorrent:
              - path: /data/downloads/torrents
                subPath: downloads/torrents
            cross-seed:
              - path: /data/downloads/torrents/complete
                subPath: downloads/torrents/complete

      config-qbitmanage:
        type: emptyDir
        advancedMounts:
          torrenting:
            qbitmanage:
              - path: /app/config
              - path: /config

      config-file-qbitmanage:
        type: secret
        name: *secret
        defaultMode: 0600
        advancedMounts:
          torrenting:
            qbitmanage:
              - path: /secret/config.yml
                subPath: config.yml
                readOnly: true

      config-cross-seed:
        type: emptyDir
        medium: Memory
        advancedMounts:
          torrenting:
            cross-seed:
              - path: /config

      config-file-cross-seed:
        type: secret
        name: qbittorrent-secret
        advancedMounts:
          torrenting:
            cross-seed:
              - path: /config/config.js
                subPath: config.js
                readOnly: true

      addons:
        type: emptyDir
        advancedMounts:
          torrenting:
            qbittorrent:
              - path: /addons
                readOnly: true
            vuetorrent:
              - path: /addons

      oauth2-proxy-config:
        type: configMap
        name: qbittorrent-oauth2-proxy-config
        advancedMounts:
          torrenting:
            oauth2-proxy:
              - path: /etc/oauth2-proxy.cfg
                subPath: oauth2-proxy.cfg
                readOnly: true
