---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      verify:
        provider: cosign
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          vpn:
            image:
              repository: qmcgaw/gluetun
              tag: v3.39@sha256:6a8058e626763cbf735ac2f78c774dbb24fec2490bd9d9f7d67e22592cb4a991
            env:
              TZ: Europe/Sofia
              VPN_TYPE: wireguard
              VPN_SERVICE_PROVIDER: protonvpn
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_LISTENING_PORT: 50413
              WIREGUARD_ADDRESSES: 10.2.0.2/32
              FIREWALL_INPUT_PORTS: 80
              FIREWALL_OUTBOUND_SUBNETS: 172.16.0.0/16,172.17.0.0/16,192.168.91.0/24
              SERVER_CITIES: Zurich
              DNS_KEEP_NAMESERVER: on
              PUID: 568
              PGID: 568
            envFrom:
              - secretRef:
                  name: gluetun-secret
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"], add: ["NET_ADMIN", "CHOWN"] }
              seccompProfile: { type: RuntimeDefault }
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                squat.ai/tun: 1
          app:
            dependsOn: vpn
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.0@sha256:1cc1878d06fafe6a1a1294f1547203634e729e3386324b7a63c8fde68554d705
            env:
              TZ: Europe/Sofia
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 50413
              CROSS_SEED_ENABLED: true
              CROSS_SEED_HOST: cross-seed.media.svc.cluster.local
              CROSS_SEED_PORT: 80
              CROSS_SEED_SLEEP_INTERVAL: 15
              PUSHOVER_ENABLED: true
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              runAsNonRoot: true
              runAsUser: 568
              runAsGroup: 568
              seccompProfile: { type: RuntimeDefault }
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 6Gi
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    terminationGracePeriodSeconds: 300
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port
          bittorrent:
            enabled: true
            port: *torrentPort
            protocol: TCP
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${PUBLIC_DOMAIN}
          kubernetes.io/ingress.class: internal
          traefik.ingress.kubernetes.io/router.middlewares: network-vuetorrent@kubernetescrd
        hosts:
          - host: "{{ .Release.Name }}.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      scripts:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        advancedMounts:
          qbittorrent:
            app:
              - readOnly: true
      media:
        type: nfs
        server: nas.${PUBLIC_DOMAIN}
        path: /mnt/exos20/data
        advancedMounts:
          qbittorrent:
            app:
              - path: /data/downloads/torrents
                subPath: downloads/torrents
      gluetun-tmp:
        enabled: true
        type: emptyDir
        advancedMounts:
          qbittorrent:
            vpn:
              - path: /tmp/gluetun
      gluetun:
        enabled: true
        type: emptyDir
        advancedMounts:
          qbittorrent:
            vpn:
              - path: /gluetun
