---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./volsync.yaml
  - ../../../../templates/gatus/guarded
configMapGenerator:
  - name: qbittorrent-loki-rules
    files:
      - qbittorrent.yaml=./resources/lokirule.yaml
    options:
      labels:
        loki_rule: "true"
  - name: qbittorrent-scripts
    files:
      - post-process.sh=./resources/post-process.sh
      - healthcheck.sh=./resources/healthcheck.sh
  - name: qbitmanage-config
    files:
      - config.yml=./resources/qbitmanage-config.yaml
  - name: qbittorrent-dnsdist
    files:
      - ./resources/dnsdist.conf
generatorOptions:
  disableNameSuffixHash: true
