apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: datavol-dest
  namespace: media
spec:
  trigger:
    manual: restore-once
  restic:
    repository: qbittorrent-volsync-secret
    # Use an existing PVC, don't provision a new one
    destinationPVC: qbittorrent-config
    copyMethod: Snapshot
    storageClassName: openebs-zfs-128k
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
