---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret cross-seed-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            delay: 30,
            duplicateCategories: true,
            flatLinking: false,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkCategory: "cross-seed",
            linkDir: "/data/torrents/complete/cross-seed",
            linkType: "hardlink",
            matchMode: "safe",
            outputDir: "/config",
            port: 80,
            qbittorrentUrl: "http://qbittorrent.media.svc.cluster.local:10095",
            radarr: ["http://radarr.media.svc.cluster.local:7878/?apikey={{ .RADARR_API_KEY }}"],
            skipRecheck: true,
            sonarr: ["http://sonarr.media.svc.cluster.local:8989/?apikey={{ .SONARR_API_KEY }}"],
            torrentDir: "/qbittorrent/qBittorrent/BT_backup",
            torznab: [
                88, // HUNO
                89, // OTW
                90, // FNP
            ].map(i => `http://prowlarr.media.svc.cluster.local:9696/$${i}/api?apikey={{ .PROWLARR_API_KEY }}`),
          };
  dataFrom:
    - extract:
        key: secrets/api-keys
