---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret omegabrr-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          server:
            host: 0.0.0.0
            port: 80
            apiToken: {{ .OMEGABRR_API_KEY }}
          clients:
            autobrr:
              host: https://autobrr.${PUBLIC_DOMAIN}
              apikey: {{ .AUTOBRR_API_KEY }}
              basicAuth:
                  user: {{ .AUTHENTIK_USER }}
                  pass: {{ .AUTHENTIK_PASSWORD }}
            arr:
              - name: radarr
                type: radarr
                host: https://radarr.${PUBLIC_DOMAIN}
                apikey: {{ .RADARR_API_KEY }}
                filters: [5]
              - name: sonarr
                type: sonarr
                host: https://sonarr.${PUBLIC_DOMAIN}
                apikey: {{ .SONARR_API_KEY }}
                basicAuth:
                  user: {{ .AUTHENTIK_USER }}
                  pass: {{ .AUTHENTIK_PASSWORD }}
                filters: [6]
                excludeAlternateTitles: true
  dataFrom:
    - extract:
        key: secrets/api-keys
    - extract:
        key: secrets/omegabrr
