---
# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/heads/master/traefik/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 32.1.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
  values:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    tlsStore:
        default:
          certificates:
            - secretName: darkfellanet-tls
          defaultCertificate:
            secretName: darkfellanet-tls
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    deployment:
      annotations:
        reloader.stakater.com/auto: "true"
      ingressClass:
        enabled: true
        isDefaultClass: false
        name: external
      enabled: true
      kind: Deployment
      replicas: null
      revisionHistoryLimit: 5
      terminationGracePeriodSeconds: 60
      minReadySeconds: 0
      healthchecksPort: 9000
      healthchecksScheme: HTTP
      additionalVolumes:
        - name: plugins
      shareProcessNamespace: false
      dnsPolicy: ""
      dnsConfig: {}
    ingressRoute:
      dashboard:
        enabled: false
      healthcheck:
        enabled: false
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: external
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: false
        allowEmptyServices: true
        ingressClass: external
        publishedService:
          enabled: false
    volumes:
      - name: crowdsec-bouncer-tls
        mountPath: /etc/traefik/crowdsec-certs
        type: secret
    additionalVolumeMounts:
      - name: plugins
        mountPath: /plugins-storage
    logs:
      general:
        level: INFO
      access:
        enabled: true
    metrics:
      addInternals: false
      prometheus:
        entryPoint: metrics
        addEntryPointsLabels: null
        addRoutersLabels: null
        addServicesLabels: null
        buckets: ""
        manualRouting: false
        service:
          enabled: true
          labels: {}
          annotations: {}
        disableAPICheck: false
    globalArguments:
      - --global.checknewversion
    additionalArguments:
      - --experimental.plugins.crowdsec-bouncer-traefik-plugin.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      - --experimental.plugins.crowdsec-bouncer-traefik-plugin.version=v1.3.3
      - --experimental.plugins.traefik-themepark.modulename=github.com/packruler/traefik-themepark
      - --experimental.plugins.traefik-themepark.version=v1.4.1
      - --experimental.plugins.traefik-real-ip.modulename=github.com/jramsgz/traefik-real-ip
      - --experimental.plugins.traefik-real-ip.version=v1.0.6
    ports:
      web:
        expose:
          default: false
      websecure:
        asDefault: true
        port: 443
        targetPort: 443
        protocol: TCP
        forwardedHeaders:
          trustedIPs:
            - 173.245.48.0/20
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 141.101.64.0/18
            - 108.162.192.0/18
            - 190.93.240.0/20
            - 188.114.96.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 162.158.0.0/15
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 172.64.0.0/13
            - 131.0.72.0/22
            - 172.16.0.0/16
          insecure: false
        transport:
          respondingTimeouts:
            readTimeout: 120
            writeTimeout: null
            idleTimeout: 180
          lifeCycle:
            requestAcceptGraceTimeout: 60
            graceTimeOut: 120
          keepAliveMaxRequests: 10000
          keepAliveMaxTime: 120
        tls:
          enabled: true
          option: default
        middlewares:
          - network-limit@kubernetescrd
          - network-chain-basic@kubernetescrd
          - network-realip@kubernetescrd
          - network-bouncer@kubernetescrd
      metrics:
        port: 9100
        expose:
          default: false
        exposedPort: 9100
        protocol: TCP
    tlsOptions:
      default:
        sniStrict: true
        minVersion: VersionTLS13
        curvePreferences:
          - CurveP521
          - CurveP384
          - X25519
    service:
      enabled: true
      single: true
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/ips: 192.168.91.95
        external-dns.alpha.kubernetes.io/hostname: external.${PUBLIC_DOMAIN}
      spec:
        allocateLoadBalancerNodePorts: false
    autoscaling:
      enabled: true
      maxReplicas: 2
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
