---
# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/heads/master/traefik/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 32.1.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
  values:
    tlsStore:
        default:
          certificates:
            - secretName: darkfellanet-tls
          defaultCertificate:
            secretName: darkfellanet-tls
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    deployment:
      ingressClass:
        enabled: true
        isDefaultClass: false
        name: external
      enabled: true
      kind: Deployment
      replicas: 2
      revisionHistoryLimit: 5
      terminationGracePeriodSeconds: 60
      minReadySeconds: 0
      healthchecksPort: 9000
      healthchecksScheme: HTTP
      additionalVolumes:
        - name: plugins
      shareProcessNamespace: false
      dnsPolicy: ""
      dnsConfig: {}
    ingressRoute:
      dashboard:
        enabled: false
      healthcheck:
        enabled: true
        matchRule: PathPrefix(`/ping`)
        services:
          - name: ping@internal
            kind: TraefikService
        entryPoints:
          - traefik
        tls: {}
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: false
        allowEmptyServices: true
        ingressClass: external
        namespaces: []
        nativeLBByDefault: false
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: false
        allowEmptyServices: true
        ingressClass: external
        namespaces: []
        publishedService:
          enabled: false
        nativeLBByDefault: false
    volumes:
      - name: crowdsec-bouncer-tls
        mountPath: /etc/traefik/crowdsec-certs
        type: secret
    additionalVolumeMounts:
      - name: plugins
        mountPath: /plugins-storage
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    metrics:
      addInternals: false
      prometheus:
        entryPoint: metrics
        addEntryPointsLabels: null
        addRoutersLabels: null
        addServicesLabels: null
        buckets: ""
        manualRouting: false
        service:
          enabled: true
          labels: {}
          annotations: {}
        disableAPICheck: false
    globalArguments:
      - --global.checknewversion
      - --global.sendanonymoususage
    additionalArguments:
      - --experimental.plugins.crowdsec-bouncer-traefik-plugin.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      - --experimental.plugins.crowdsec-bouncer-traefik-plugin.version=v1.3.4
      - --experimental.plugins.traefik-themepark.modulename=github.com/packruler/traefik-themepark
      - --experimental.plugins.traefik-themepark.version=v1.4.0
      - --experimental.plugins.traefik-real-ip.modulename=github.com/jramsgz/traefik-real-ip
      - --experimental.plugins.traefik-real-ip.version=v1.0.6
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
    ports:
      web:
        expose:
          default: false
        port: 80
        targetPort: 80
        protocol: TCP
        forwardedHeaders:
          trustedIPs:
            - 173.245.48.0/20
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 141.101.64.0/18
            - 108.162.192.0/18
            - 190.93.240.0/20
            - 188.114.96.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 162.158.0.0/15
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 172.64.0.0/13
            - 131.0.72.0/22
          insecure: false
        proxyProtocol:
          trustedIPs: []
          insecure: false
        redirectTo:
          name: websecure
        transport:
          respondingTimeouts:
            readTimeout: null
            writeTimeout: null
            idleTimeout: null
          lifeCycle:
            requestAcceptGraceTimeout: null
            graceTimeOut: null
          keepAliveMaxRequests: null
          keepAliveMaxTime: null
      websecure:
        asDefault: true
        port: 443
        targetPort: 443
        protocol: TCP
        appProtocol: null
        allowACMEByPass: false
        http3:
          enabled: false
          advertisedPort: null
        forwardedHeaders:
          trustedIPs:
            - 173.245.48.0/20
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 141.101.64.0/18
            - 108.162.192.0/18
            - 190.93.240.0/20
            - 188.114.96.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 162.158.0.0/15
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 172.64.0.0/13
            - 131.0.72.0/22
          insecure: false
        proxyProtocol:
          trustedIPs: []
          insecure: false
        transport:
          respondingTimeouts:
            readTimeout: null
            writeTimeout: null
            idleTimeout: null
          lifeCycle:
            requestAcceptGraceTimeout: null
            graceTimeOut: null
          keepAliveMaxRequests: null
          keepAliveMaxTime: null
        tls:
          enabled: true
        middlewares:
          - network-realip@kubernetescrd
          - network-bouncer@kubernetescrd
          - network-chain-basic@kubernetescrd
          - network-compress@kubernetescrd
      metrics:
        port: 9100
        expose:
          default: false
        exposedPort: 9100
        protocol: TCP
    tlsOptions:
      default:
        sniStrict: true
        minVersion: VersionTLS13
        curvePreferences:
          - CurveP521
          - CurveP384
          - X25519
    service:
      enabled: true
      single: true
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/ips: 192.168.91.95
        external-dns.alpha.kubernetes.io/hostname: external.${PUBLIC_DOMAIN}
      spec:
        allocateLoadBalancerNodePorts: false
    autoscaling:
      enabled: false
    hostNetwork: false
    rbac:
      enabled: true
      namespaced: false
