---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: topolvm
spec:
  interval: 30m
  chart:
    spec:
      chart: topolvm
      version: 15.4.0
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
      - kind: ConfigMap
        name: topolvm-helm-values
