lvmd:
  managed: false
  deviceClasses:
    - name: thin
      volume-group: topolvm_vg
      type: thin
      default: true
      thin-pool:
        name: topolvm_thin
        overprovision-ratio: 15.0
node:
  lvmdEmbedded: true
controller:
  replicaCount: 1

