lvmd:
  managed: true
  deviceClasses:
    - name: thin
      volume-group: topolvm_vg
      type: thin
      default: true
      thin-pool:
        name: topolvm_thin
        overprovision-ratio: 15.0
controller:
  replicaCount: 1
  updateStrategy:
    type: Recreate
storageClasses:
  - name: topolvm-provisioner-thin
    storageClass:
      fsType: xfs
      isDefaultClass: true
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        "topolvm.io/device-class": "thin"
